// Copyright 2025 Bloxide, all rights reserved
//! Concrete supervisor spec for in-crate testing.
//!
//! The blox-crate-level `SupervisorSpec` (in `generated/spec_skeleton.rs`)
//! contains **stub** action closures — per invariant #18, concrete actions
//! are only linked at the system level via `system.toml` codegen.
//!
//! This module provides a `ConcreteSupervisorSpec<R>` that wires the real
//! platform action functions (`bloxide_child_management::actions::*`) with
//! payload extraction, so that in-crate tests can verify actual supervisor
//! behavior without needing a system.toml. System-level apps get their own
//! concrete spec generated by the codegen.

use crate::generated::topology::SupervisorState;
use crate::{SupervisorCtx, SupervisorEvent};
use bloxide_child_management::control::ChildCtrl;
use bloxide_core::capability::BloxRuntime;
use bloxide_core::lifecycle::ChildLifecycleEvent;
use bloxide_core::messaging::Envelope;
use bloxide_core::spec::{MachineSpec, StateFns};
use bloxide_core::topology::LeafState;
use bloxide_core::transition::{ActionResult, Decision, StateRule};
use core::marker::PhantomData;

pub struct ConcreteSupervisorSpec<R: BloxRuntime> {
    _phantom: PhantomData<R>,
}

/// Flush pending commands — the first action on nearly every rule
/// (confirm-before-record: commands lost to a full channel are retried on
/// every event pass; a Closed channel observed while flushing marks the
/// child Gone, terminal evidence the guards read directly from the group).
fn flush<R: BloxRuntime>(ctx: &mut SupervisorCtx<R>) {
    bloxide_child_management::actions::flush_pending(ctx.self_id, &mut ctx.children);
}

impl<R: BloxRuntime> ConcreteSupervisorSpec<R> {
    const RUNNING_FNS: StateFns<Self> = StateFns {
        on_entry: &[|ctx| {
            bloxide_child_management::actions::start_children(ctx.self_id, &mut ctx.children);
        }],
        on_exit: &[],
        transitions: &[
            StateRule {
                event_tag: SupervisorEvent::<R>::CHILD_TAG,
                matches: |ev| {
                    matches!(
                        ev,
                        SupervisorEvent::Child(Envelope(_, ChildLifecycleEvent::Stopped { .. }))
                    )
                },
                actions: &[
                    |ctx, _ev| {
                        flush(ctx);
                        ActionResult::Ok
                    },
                    |ctx, ev| {
                        if let Some(payload) = ev.child_payload() {
                            bloxide_child_management::actions::handle_done_or_failed(
                                ctx.self_id,
                                &mut ctx.children,
                                &ctx.child_notify,
                                payload,
                            );
                        }
                        ActionResult::Ok
                    },
                ],
                guard: |ctx, _results, _ev| {
                    if ctx.all_children_stopped() {
                        Decision::Stop
                    } else if ctx.children.should_begin_shutdown() {
                        Decision::Transition(LeafState::new(SupervisorState::ShuttingDown))
                    } else {
                        Decision::Stay
                    }
                },
            },
            StateRule {
                event_tag: SupervisorEvent::<R>::CHILD_TAG,
                matches: |ev| {
                    matches!(
                        ev,
                        SupervisorEvent::Child(Envelope(_, ChildLifecycleEvent::Failed { .. }))
                    )
                },
                actions: &[
                    |ctx, _ev| {
                        flush(ctx);
                        ActionResult::Ok
                    },
                    |ctx, ev| {
                        if let Some(payload) = ev.child_payload() {
                            bloxide_child_management::actions::handle_done_or_failed(
                                ctx.self_id,
                                &mut ctx.children,
                                &ctx.child_notify,
                                payload,
                            );
                        }
                        ActionResult::Ok
                    },
                ],
                guard: |ctx, _results, _ev| {
                    if ctx.all_children_stopped() {
                        Decision::Stop
                    } else if ctx.children.should_begin_shutdown() {
                        Decision::Transition(LeafState::new(SupervisorState::ShuttingDown))
                    } else {
                        Decision::Stay
                    }
                },
            },
            StateRule {
                event_tag: SupervisorEvent::<R>::CHILD_TAG,
                matches: |ev| {
                    matches!(
                        ev,
                        SupervisorEvent::Child(Envelope(_, ChildLifecycleEvent::Started { .. }))
                    )
                },
                actions: &[
                    |ctx, _ev| {
                        flush(ctx);
                        ActionResult::Ok
                    },
                    |ctx, ev| {
                        if let Some(payload) = ev.child_payload() {
                            bloxide_child_management::actions::record_started(
                                ctx.self_id,
                                &mut ctx.children,
                                payload,
                            );
                        }
                        ActionResult::Ok
                    },
                ],
                guard: |ctx, _results, _ev| {
                    if ctx.all_children_stopped() {
                        Decision::Stop
                    } else if ctx.children.should_begin_shutdown() {
                        Decision::Transition(LeafState::new(SupervisorState::ShuttingDown))
                    } else {
                        Decision::Stay
                    }
                },
            },
            StateRule {
                event_tag: SupervisorEvent::<R>::CHILD_TAG,
                matches: |ev| {
                    matches!(
                        ev,
                        SupervisorEvent::Child(Envelope(_, ChildLifecycleEvent::Aborted { .. }))
                    )
                },
                actions: &[
                    |ctx, _ev| {
                        flush(ctx);
                        ActionResult::Ok
                    },
                    |ctx, ev| {
                        if let Some(payload) = ev.child_payload() {
                            bloxide_child_management::actions::record_aborted(
                                ctx.self_id,
                                &mut ctx.children,
                                payload,
                            );
                        }
                        ActionResult::Ok
                    },
                ],
                guard: |ctx, _results, _ev| {
                    if ctx.all_children_stopped() {
                        Decision::Stop
                    } else if ctx.children.should_begin_shutdown() {
                        Decision::Transition(LeafState::new(SupervisorState::ShuttingDown))
                    } else {
                        Decision::Stay
                    }
                },
            },
            StateRule {
                event_tag: SupervisorEvent::<R>::CHILD_TAG,
                matches: |ev| {
                    matches!(
                        ev,
                        SupervisorEvent::Child(Envelope(_, ChildLifecycleEvent::Killed { .. }))
                    )
                },
                actions: &[
                    |ctx, _ev| {
                        flush(ctx);
                        ActionResult::Ok
                    },
                    |ctx, ev| {
                        if let Some(payload) = ev.child_payload() {
                            bloxide_child_management::actions::record_killed(
                                ctx.self_id,
                                &mut ctx.children,
                                payload,
                            );
                        }
                        ActionResult::Ok
                    },
                ],
                guard: |ctx, _results, _ev| {
                    if ctx.all_children_stopped() {
                        Decision::Stop
                    } else if ctx.children.should_begin_shutdown() {
                        Decision::Transition(LeafState::new(SupervisorState::ShuttingDown))
                    } else {
                        Decision::Stay
                    }
                },
            },
            StateRule {
                event_tag: SupervisorEvent::<R>::CHILD_TAG,
                matches: |ev| {
                    matches!(
                        ev,
                        SupervisorEvent::Child(Envelope(_, ChildLifecycleEvent::Alive { .. }))
                    )
                },
                actions: &[
                    |ctx, _ev| {
                        flush(ctx);
                        ActionResult::Ok
                    },
                    |ctx, ev| {
                        if let Some(payload) = ev.child_payload() {
                            bloxide_child_management::actions::record_alive(
                                &mut ctx.children,
                                payload,
                            );
                        }
                        ActionResult::Ok
                    },
                ],
                guard: |ctx, _results, _ev| {
                    if ctx.all_children_stopped() {
                        Decision::Stop
                    } else if ctx.children.should_begin_shutdown() {
                        Decision::Transition(LeafState::new(SupervisorState::ShuttingDown))
                    } else {
                        Decision::Stay
                    }
                },
            },
            StateRule {
                event_tag: SupervisorEvent::<R>::CHILD_TAG,
                matches: |ev| {
                    matches!(
                        ev,
                        SupervisorEvent::Child(Envelope(_, ChildLifecycleEvent::Done { .. }))
                    )
                },
                actions: &[
                    |ctx, _ev| {
                        flush(ctx);
                        ActionResult::Ok
                    },
                    |ctx, ev| {
                        if let Some(payload) = ev.child_payload() {
                            bloxide_child_management::actions::deregister_done(
                                ctx.self_id,
                                &mut ctx.children,
                                payload,
                            );
                        }
                        ActionResult::Ok
                    },
                ],
                guard: |ctx, _results, _ev| {
                    if ctx.all_children_stopped() {
                        Decision::Stop
                    } else if ctx.children.should_begin_shutdown() {
                        Decision::Transition(LeafState::new(SupervisorState::ShuttingDown))
                    } else {
                        Decision::Stay
                    }
                },
            },
            StateRule {
                event_tag: SupervisorEvent::<R>::CONTROL_TAG,
                matches: |ev| {
                    matches!(
                        ev,
                        SupervisorEvent::Control(Envelope(_, ChildCtrl::RegisterChild(_)))
                    )
                },
                actions: &[
                    |ctx, _ev| {
                        flush(ctx);
                        ActionResult::Ok
                    },
                    |ctx, ev| {
                        if let Some(ctrl) = ev.control_payload() {
                            bloxide_child_management::actions::register_child(
                                ctx.self_id,
                                &mut ctx.children,
                                ctrl,
                            );
                        }
                        ActionResult::Ok
                    },
                ],
                guard: |ctx, _results, _ev| {
                    if ctx.all_children_stopped() {
                        Decision::Stop
                    } else if ctx.children.should_begin_shutdown() {
                        Decision::Transition(LeafState::new(SupervisorState::ShuttingDown))
                    } else {
                        Decision::Stay
                    }
                },
            },
            StateRule {
                event_tag: SupervisorEvent::<R>::CONTROL_TAG,
                matches: |ev| {
                    matches!(
                        ev,
                        SupervisorEvent::Control(Envelope(_, ChildCtrl::RegisterDynamicChild(_)))
                    )
                },
                actions: &[
                    |ctx, _ev| {
                        flush(ctx);
                        ActionResult::Ok
                    },
                    |ctx, ev| {
                        if let Some(ctrl) = ev.control_payload() {
                            bloxide_child_management::actions::handle_register_dynamic_child(
                                ctx.self_id,
                                &mut ctx.children,
                                ctrl,
                            );
                        }
                        ActionResult::Ok
                    },
                ],
                guard: |ctx, _results, _ev| {
                    if ctx.all_children_stopped() {
                        Decision::Stop
                    } else if ctx.children.should_begin_shutdown() {
                        Decision::Transition(LeafState::new(SupervisorState::ShuttingDown))
                    } else {
                        Decision::Stay
                    }
                },
            },
            StateRule {
                event_tag: SupervisorEvent::<R>::CONTROL_TAG,
                matches: |ev| {
                    matches!(
                        ev,
                        SupervisorEvent::Control(Envelope(_, ChildCtrl::WatchdogTick))
                    )
                },
                actions: &[
                    |ctx, _ev| {
                        flush(ctx);
                        ActionResult::Ok
                    },
                    |ctx, ev| {
                        if let Some(ctrl) = ev.control_payload() {
                            bloxide_child_management::actions::handle_watchdog_tick(
                                ctx.self_id,
                                &mut ctx.children,
                                &ctx.child_notify,
                                ctrl,
                            );
                        }
                        ActionResult::Ok
                    },
                ],
                guard: |ctx, _results, _ev| {
                    if ctx.all_children_stopped() {
                        Decision::Stop
                    } else if ctx.children.should_begin_shutdown() {
                        Decision::Transition(LeafState::new(SupervisorState::ShuttingDown))
                    } else {
                        Decision::Stay
                    }
                },
            },
            // No Running catch-alls: the rules above cover every
            // ChildLifecycleEvent and ChildCtrl variant, so
            // `SupervisorEvent::Child(_)` / `SupervisorEvent::Control(_)`
            // rules would share the event_tag of the specific rules, be
            // evaluated last, and never match — unreachable dead code.
            // (Mirrors the codegen, which omits fully-covered catch-alls
            // declared in blox.toml; ShuttingDown below keeps its catch-alls
            // because coverage there is partial.)
        ],
    };

    const SHUTTING_DOWN_FNS: StateFns<Self> = StateFns {
        on_entry: &[|ctx| {
            bloxide_child_management::actions::stop_all_children(ctx.self_id, &mut ctx.children);
        }],
        on_exit: &[],
        transitions: &[
            StateRule {
                event_tag: SupervisorEvent::<R>::CHILD_TAG,
                matches: |ev| {
                    matches!(
                        ev,
                        SupervisorEvent::Child(Envelope(_, ChildLifecycleEvent::Stopped { .. }))
                    )
                },
                actions: &[
                    |ctx, _ev| {
                        flush(ctx);
                        ActionResult::Ok
                    },
                    |ctx, ev| {
                        if let Some(payload) = ev.child_payload() {
                            bloxide_child_management::actions::record_stopped(
                                ctx.self_id,
                                &mut ctx.children,
                                payload,
                            );
                        }
                        ActionResult::Ok
                    },
                ],
                guard: |ctx, _results, _ev| {
                    if ctx.all_children_stopped() {
                        Decision::Stop
                    } else {
                        Decision::Stay
                    }
                },
            },
            StateRule {
                event_tag: SupervisorEvent::<R>::CHILD_TAG,
                matches: |ev| {
                    matches!(
                        ev,
                        SupervisorEvent::Child(Envelope(_, ChildLifecycleEvent::Done { .. }))
                    )
                },
                actions: &[
                    |ctx, _ev| {
                        flush(ctx);
                        ActionResult::Ok
                    },
                    |ctx, ev| {
                        if let Some(payload) = ev.child_payload() {
                            bloxide_child_management::actions::deregister_done(
                                ctx.self_id,
                                &mut ctx.children,
                                payload,
                            );
                        }
                        ActionResult::Ok
                    },
                ],
                guard: |ctx, _results, _ev| {
                    if ctx.all_children_stopped() {
                        Decision::Stop
                    } else {
                        Decision::Stay
                    }
                },
            },
            StateRule {
                event_tag: SupervisorEvent::<R>::CHILD_TAG,
                matches: |ev| {
                    matches!(
                        ev,
                        SupervisorEvent::Child(Envelope(_, ChildLifecycleEvent::Failed { .. }))
                    )
                },
                actions: &[
                    |ctx, _ev| {
                        flush(ctx);
                        ActionResult::Ok
                    },
                    |ctx, ev| {
                        if let Some(payload) = ev.child_payload() {
                            bloxide_child_management::actions::record_failed(
                                ctx.self_id,
                                &mut ctx.children,
                                payload,
                            );
                        }
                        ActionResult::Ok
                    },
                ],
                guard: |ctx, _results, _ev| {
                    if ctx.all_children_stopped() {
                        Decision::Stop
                    } else {
                        Decision::Stay
                    }
                },
            },
            StateRule {
                event_tag: SupervisorEvent::<R>::CHILD_TAG,
                matches: |ev| {
                    matches!(
                        ev,
                        SupervisorEvent::Child(Envelope(_, ChildLifecycleEvent::Aborted { .. }))
                    )
                },
                actions: &[
                    |ctx, _ev| {
                        flush(ctx);
                        ActionResult::Ok
                    },
                    |ctx, ev| {
                        if let Some(payload) = ev.child_payload() {
                            bloxide_child_management::actions::record_aborted(
                                ctx.self_id,
                                &mut ctx.children,
                                payload,
                            );
                        }
                        ActionResult::Ok
                    },
                ],
                guard: |ctx, _results, _ev| {
                    if ctx.all_children_stopped() {
                        Decision::Stop
                    } else {
                        Decision::Stay
                    }
                },
            },
            StateRule {
                event_tag: SupervisorEvent::<R>::CHILD_TAG,
                matches: |ev| {
                    matches!(
                        ev,
                        SupervisorEvent::Child(Envelope(_, ChildLifecycleEvent::Killed { .. }))
                    )
                },
                actions: &[
                    |ctx, _ev| {
                        flush(ctx);
                        ActionResult::Ok
                    },
                    |ctx, ev| {
                        if let Some(payload) = ev.child_payload() {
                            bloxide_child_management::actions::record_killed(
                                ctx.self_id,
                                &mut ctx.children,
                                payload,
                            );
                        }
                        ActionResult::Ok
                    },
                ],
                guard: |ctx, _results, _ev| {
                    if ctx.all_children_stopped() {
                        Decision::Stop
                    } else {
                        Decision::Stay
                    }
                },
            },
            // WatchdogTick in ShuttingDown: flush pending commands only
            // (no health checks — children are being stopped, not monitored).
            StateRule {
                event_tag: SupervisorEvent::<R>::CONTROL_TAG,
                matches: |ev| {
                    matches!(
                        ev,
                        SupervisorEvent::Control(Envelope(_, ChildCtrl::WatchdogTick))
                    )
                },
                actions: &[|ctx, _ev| {
                    flush(ctx);
                    ActionResult::Ok
                }],
                guard: |ctx, _results, _ev| {
                    if ctx.all_children_stopped() {
                        Decision::Stop
                    } else {
                        Decision::Stay
                    }
                },
            },
            // Catch-all: any other Child event → absorb
            StateRule {
                event_tag: SupervisorEvent::<R>::CHILD_TAG,
                matches: |ev| matches!(ev, SupervisorEvent::Child(_)),
                actions: &[],
                guard: |_ctx, _results, _ev| Decision::Stay,
            },
            // Catch-all: any Control event → absorb
            StateRule {
                event_tag: SupervisorEvent::<R>::CONTROL_TAG,
                matches: |ev| matches!(ev, SupervisorEvent::Control(_)),
                actions: &[],
                guard: |_ctx, _results, _ev| Decision::Stay,
            },
        ],
    };
}

impl<R: BloxRuntime> MachineSpec for ConcreteSupervisorSpec<R> {
    type State = SupervisorState;
    type Event = SupervisorEvent<R>;
    type Ctx = SupervisorCtx<R>;
    type Mailboxes<Rt: BloxRuntime> = (Rt::Stream<ChildLifecycleEvent>, Rt::Stream<ChildCtrl<R>>);
    const HANDLER_TABLE: &'static [&'static StateFns<Self>] =
        &[&Self::RUNNING_FNS, &Self::SHUTTING_DOWN_FNS];
    fn initial_state() -> SupervisorState {
        SupervisorState::Running
    }
    fn is_error(_state: &SupervisorState) -> bool {
        false
    }
    // No `on_init_entry` override: Reset skips Init entirely (the engine goes
    // straight to initial_state), and Running's on_entry (start_children)
    // clears the child counters on every entry — initial Start, re-Start
    // after Stop, and Reset alike — so Init-entry cleanup is redundant.
}
