// Copyright 2025 Bloxide, all rights reserved
//! Scaffold a new messages crate.

use anyhow::Result;
use std::fs;
use std::path::Path;

use crate::utils::{
    to_camel_case, update_workspace_cargo_toml, workspace_root_or_cwd, WorkspaceAddition,
};

pub fn new_messages(name: &str) -> Result<()> {
    let root = workspace_root_or_cwd()?;
    new_messages_in(&root, name)
}

pub(crate) fn new_messages_in(root: &Path, name: &str) -> Result<()> {
    let name_snake = name.to_lowercase().replace("-", "_");
    let name_camel = to_camel_case(name);
    let crate_name = format!("{}-messages", name_snake);

    let crate_dir = root.join("crates/messages").join(&crate_name);
    let src_dir = crate_dir.join("src");
    let gen_dir = src_dir.join("generated");
    fs::create_dir_all(&gen_dir)?;

    let cargo_toml = format!(
        r#"# Copyright 2025 Bloxide, all rights reserved
[package]
name = "{crate_name}"
version.workspace = true
edition.workspace = true
description = "Domain message types for {name_camel}"
repository.workspace = true
license.workspace = true

[dependencies]
bloxide-macros = {{ workspace = true }}
"#
    );
    fs::write(crate_dir.join("Cargo.toml"), cargo_toml)?;

    let lib_rs = format!(
        r#"// Copyright 2025 Bloxide, all rights reserved
#![no_std]

pub mod generated;
pub mod prelude;

pub use generated::{{{name_camel}Msg, Tick}};
"#
    );
    fs::write(src_dir.join("lib.rs"), lib_rs)?;

    let prelude_rs = format!(
        r#"// Copyright 2025 Bloxide, all rights reserved
/// Convenience re-exports for the {name} message types.
pub use crate::{{{name_camel}Msg, Tick}};
"#
    );
    fs::write(src_dir.join("prelude.rs"), prelude_rs)?;

    let gen_mod_rs =
        "// Auto-generated module.\n// Files in this directory are generated by bloxide-codegen.\n//! Generated by bloxide-codegen from blox.toml — do not edit by hand; regenerate with `cargo blox generate`.\n";
    fs::write(gen_dir.join("mod.rs"), gen_mod_rs)?;

    let blox_toml = format!(
        r#"# Copyright 2025 Bloxide, all rights reserved
[[messages]]
name = "{name_camel}Msg"
visibility = "pub"

  [[messages.variants]]
  name = "Tick"
"#
    );
    fs::write(crate_dir.join("blox.toml"), blox_toml)?;

    let member_path = format!("crates/messages/{}", crate_name);
    let dep_toml_line = format!(
        r#"{} = {{ path = "crates/messages/{}" }}"#,
        crate_name, crate_name
    );
    update_workspace_cargo_toml(
        root,
        &[
            WorkspaceAddition::Member(member_path),
            WorkspaceAddition::Dependency {
                name: crate_name,
                toml_line: dep_toml_line,
            },
        ],
    )?;

    println!("Created: {}", crate_dir.display());
    Ok(())
}
