// Copyright 2025 Bloxide, all rights reserved

use bloxide_codegen::generate_all;
use bloxide_codegen::schema::BloxConfig;

#[test]
fn parse_counter_messages_toml() {
    let toml = r#"
[[messages]]
name = "CounterMsg"
visibility = "pub"

[[messages.variants]]
name = "Tick"
"#;

    let config: BloxConfig = toml::from_str(toml).expect("parse failed");
    let messages = config.messages.expect("messages section missing");
    assert_eq!(messages.len(), 1);
    assert_eq!(messages[0].name, "CounterMsg");
    assert_eq!(messages[0].variants.len(), 1);
    assert_eq!(messages[0].variants[0].name, "Tick");
    assert!(messages[0].variants[0].fields.is_empty());
}

#[test]
fn generate_counter_messages() {
    let toml = r#"
[[messages]]
name = "CounterMsg"
visibility = "pub"
copy = true

[[messages.variants]]
name = "Tick"
"#;

    let config: BloxConfig = toml::from_str(toml).expect("parse failed");
    let files = generate_all(&config, "counter-messages").expect("generate failed");

    let msg_file = files
        .iter()
        .find(|(n, _)| n == "messages_countermsg.rs")
        .expect("messages file missing");
    let (_name, content) = msg_file;

    // Header
    assert!(content.contains("// Auto-generated by bloxide-codegen. Do not edit manually."));

    // Unit struct for empty fields
    assert!(content.contains("pub struct Tick;"));

    // Enum with wrapper variant
    assert!(content.contains("pub enum CounterMsg {"));
    assert!(content.contains("Tick(Tick),"));

    // Derives — Copy is present because copy = true
    assert!(content.contains("#[derive(Debug, Clone, Copy)]"));

    // message_name method
    assert!(content.contains("pub fn message_name(&self) -> &'static str {"));
    assert!(content.contains("CounterMsg::Tick(..) => \"Tick\""));
}

#[test]
fn generate_messages_no_copy_by_default() {
    let toml = r#"
[[messages]]
name = "CounterMsg"
visibility = "pub"

[[messages.variants]]
name = "Tick"
"#;

    let config: BloxConfig = toml::from_str(toml).expect("parse failed");
    let files = generate_all(&config, "counter-messages").expect("generate failed");

    let msg_file = files
        .iter()
        .find(|(n, _)| n == "messages_countermsg.rs")
        .expect("messages file missing");
    let (_name, content) = msg_file;

    // Default: Debug + Clone, but NOT Copy in the derive attribute
    assert!(content.contains("Debug"));
    assert!(content.contains("Clone"));
    assert!(!content.contains("#[derive(Debug, Clone, Copy)]"));
}

#[test]
fn generate_ping_pong_messages() {
    let toml = r#"
[[messages]]
name = "PingPongMsg"
visibility = "pub"
copy = true

[[messages.variants]]
name = "Ping"
[[messages.variants.fields]]
name = "round"
ty = "u32"

[[messages.variants]]
name = "Pong"
[[messages.variants.fields]]
name = "round"
ty = "u32"

[[messages.variants]]
name = "Resume"
"#;

    let config: BloxConfig = toml::from_str(toml).expect("parse failed");
    let files = generate_all(&config, "ping-pong-messages").expect("generate failed");

    let msg_file = files
        .iter()
        .find(|(n, _)| n == "messages_pingpongmsg.rs")
        .expect("messages file missing");
    let (_name, content) = msg_file;

    // Named field structs
    assert!(content.contains("pub struct Ping {"));
    assert!(content.contains("pub round: u32,"));
    assert!(content.contains("pub struct Pong {"));
    assert!(content.contains("pub struct Resume;"));

    // Enum
    assert!(content.contains("pub enum PingPongMsg {"));
    assert!(content.contains("Ping(Ping),"));
    assert!(content.contains("Pong(Pong),"));
    assert!(content.contains("Resume(Resume),"));

    // message_name match arms
    assert!(content.contains("PingPongMsg::Ping(..) => \"Ping\""));
    assert!(content.contains("PingPongMsg::Pong(..) => \"Pong\""));
    assert!(content.contains("PingPongMsg::Resume(..) => \"Resume\""));
}

#[test]
fn generate_counter_event() {
    let toml = r#"
[actor]
name = "Counter"

[event]
name = "CounterEvent"

[[event.mailboxes]]
variant = "Msg"
message = "CounterMsg"
message_path = "counter_messages::CounterMsg"
"#;

    let config: BloxConfig = toml::from_str(toml).expect("parse failed");
    let files = generate_all(&config, "counter-blox").expect("generate failed");

    let events_file = files
        .iter()
        .find(|(n, _)| n == "events.rs")
        .expect("events.rs missing");
    let content = &events_file.1;

    // Imports
    assert!(content.contains("use ::bloxide_core::messaging::Envelope;"));

    // Enum definition
    assert!(content.contains("pub enum CounterEvent {"));
    assert!(content.contains("Lifecycle("));
    assert!(content.contains("Msg(Envelope<counter_messages::CounterMsg>),"));

    // From impls
    assert!(content.contains(
        "impl ::core::convert::From<Envelope<counter_messages::CounterMsg>> for CounterEvent"
    ));
    assert!(
        content.contains("impl ::core::convert::From<::bloxide_core::lifecycle::LifecycleCommand>")
    );

    // EventTag
    assert!(content.contains("impl ::bloxide_core::event_tag::EventTag for CounterEvent"));
    assert!(content.contains("Self::Lifecycle(..) => ::bloxide_core::event_tag::LIFECYCLE_TAG"));
    assert!(content.contains("Self::Msg(..) => 0u8"));

    // LifecycleEvent
    assert!(content.contains("impl ::bloxide_core::event_tag::LifecycleEvent for CounterEvent"));
    assert!(content.contains("fn as_lifecycle_command("));

    // Tag constants
    assert!(content.contains("pub const MSG_TAG: u8 = 0u8;"));

    // Accessor methods
    assert!(content.contains("pub fn msg_envelope("));
    assert!(content.contains("pub fn msg_payload("));

    // Lifecycle helpers
    assert!(content.contains("pub fn start() -> Self"));
    assert!(content.contains("pub fn reset() -> Self"));
    assert!(content.contains("pub fn stop() -> Self"));
    assert!(content.contains("pub fn ping() -> Self"));
}

#[test]
fn generate_event_with_custom_derives() {
    let toml = r#"
[actor]
name = "Counter"

[event]
name = "CounterEvent"
derives = ["Debug", "Clone", "PartialEq"]

[[event.mailboxes]]
variant = "Msg"
message = "CounterMsg"
message_path = "counter_messages::CounterMsg"
"#;

    let config: BloxConfig = toml::from_str(toml).expect("parse failed");
    let files = generate_all(&config, "counter-blox").expect("generate failed");

    let events_file = files
        .iter()
        .find(|(n, _)| n == "events.rs")
        .expect("events.rs missing");
    let content = &events_file.1;

    // All three custom derives should appear
    assert!(content.contains("#[derive(Debug, Clone, PartialEq)]"));
}

#[test]
fn generate_event_with_empty_derives() {
    let toml = r#"
[actor]
name = "Worker"

[event]
name = "WorkerEvent"
generics = "<R: BloxRuntime>"
derives = []

[[event.mailboxes]]
variant = "Msg"
message = "WorkerMsg"
message_path = "pool_messages::WorkerMsg"
"#;

    let config: BloxConfig = toml::from_str(toml).expect("parse failed");
    let files = generate_all(&config, "worker-blox").expect("generate failed");

    let events_file = files
        .iter()
        .find(|(n, _)| n == "events.rs")
        .expect("events.rs missing");
    let content = &events_file.1;

    // No derive attribute at all
    assert!(!content.contains("#[derive"));
    assert!(content.contains("pub enum WorkerEvent"));
}

#[test]
fn generate_event_generic_used_after_comma_no_phantom() {
    // R appears as a type argument after a comma (PeerCtrl<WorkerMsg, R>) —
    // the enum genuinely uses its generic, so no _Phantom marker is emitted.
    let toml = r#"
[actor]
name = "Worker"

[event]
name = "WorkerEvent"
generics = "<R: BloxRuntime>"
derives = []

[[event.mailboxes]]
variant = "Ctrl"
message = "PeerCtrl<WorkerMsg>"
message_path = "bloxide_peers::PeerCtrl<pool_messages::WorkerMsg, R>"

[[event.mailboxes]]
variant = "Msg"
message = "WorkerMsg"
message_path = "pool_messages::WorkerMsg"
"#;

    let config: BloxConfig = toml::from_str(toml).expect("parse failed");
    let files = generate_all(&config, "worker-blox").expect("generate failed");

    let events_file = files
        .iter()
        .find(|(n, _)| n == "events.rs")
        .expect("events.rs missing");
    let content = &events_file.1;

    assert!(!content.contains("_Phantom"));
}

#[test]
fn generate_event_generic_unused_emits_phantom() {
    // R is declared but no mailbox payload mentions it — the phantom marker
    // is required to consume the generic parameter.
    let toml = r#"
[actor]
name = "Pool"

[event]
name = "PoolEvent"
generics = "<R: BloxRuntime>"

[[event.mailboxes]]
variant = "Msg"
message = "PoolMsg"
message_path = "pool_messages::PoolMsg"
"#;

    let config: BloxConfig = toml::from_str(toml).expect("parse failed");
    let files = generate_all(&config, "pool-blox").expect("generate failed");

    let events_file = files
        .iter()
        .find(|(n, _)| n == "events.rs")
        .expect("events.rs missing");
    let content = &events_file.1;

    assert!(content.contains("#[doc(hidden)]"));
    assert!(content.contains("_Phantom(::core::marker::PhantomData<R>)"));
    assert!(content.contains("Self::_Phantom(..) => ::bloxide_core::event_tag::WILDCARD_TAG"));
}

#[test]
fn generate_event_feature_pair_phantom_only_in_non_feature_variant() {
    // Paired #[cfg] generation: the non-dynamic variant has only the
    // non-generic Msg mailbox (phantom required); the dynamic variant's
    // SpawnReply payload uses R in nested generics after commas
    // (SpawnedWorker<PeerCtrl<WorkerMsg, R>, R>), so it gets no phantom.
    let toml = r#"
[actor]
name = "Pool"

[event]
name = "PoolEvent"
generics = "<R: BloxRuntime>"
feature = "dynamic"
feature_generics = "<R: BloxRuntime>"

[[event.mailboxes]]
variant = "Msg"
message = "PoolMsg"
message_path = "pool_messages::PoolMsg"

[[event.mailboxes]]
variant = "SpawnReply"
message = "SpawnedWorker"
message_path = "blox_ctx_pool_ref::SpawnedWorker<bloxide_peers::PeerCtrl<pool_messages::WorkerMsg, R>, R>"
feature = "dynamic"
"#;

    let config: BloxConfig = toml::from_str(toml).expect("parse failed");
    let files = generate_all(&config, "pool-blox").expect("generate failed");

    let events_file = files
        .iter()
        .find(|(n, _)| n == "events.rs")
        .expect("events.rs missing");
    let content = &events_file.1;

    // Exactly one variant carries the marker: the enum variant plus its
    // EventTag wildcard arm.
    assert_eq!(content.matches("_Phantom").count(), 2);
    let non_feature = content
        .split("#[cfg(feature = \"dynamic\")]")
        .next()
        .expect("non-feature section missing");
    assert!(non_feature.contains("_Phantom(::core::marker::PhantomData<R>)"));
}
