// Copyright 2025 Bloxide, all rights reserved
use core::task::{Context, Poll};

// ── Mailboxes trait ───────────────────────────────────────────────────────────

/// A set of typed mailboxes that together produce a unified event stream.
///
/// `poll_next` returns:
/// - `Poll::Ready(Some(event))` when any stream has a message.
/// - `Poll::Ready(None)` when **all** streams have closed — no domain sender
///   remains anywhere, so the actor cannot be reached at all. This signals
///   graceful shutdown for the actor; callers should stop polling and return.
/// - `Poll::Pending` when no message is ready but at least one stream is
///   still open.
///
/// Implementations poll their constituent streams in **priority order**: the
/// first stream in the tuple is always polled first. When it has a message,
/// that message is returned immediately without checking later streams.
///
/// # Priority Convention
///
/// Place the highest-priority message type at index 0. For actors supervised
/// by the runtime, lifecycle commands (Start, Reset, Stop) flow through
/// `dispatch()` at the VirtualRoot level — they are intercepted before
/// reaching user-declared states. Order domain streams by descending urgency.
///
/// # All-streams-close semantics (issue #134)
///
/// A single closed stream does **not** shut down the actor. Domain mailbox
/// closes are a garbage-collection backstop, not a lifecycle signal — actor
/// fate is owned exclusively by supervision (dispatch-driven lifecycle plus
/// the kill capability). A peer dropping its `ActorRef` merely closes one
/// stream; the actor keeps running as long as any domain sender remains.
/// `poll_next` returns `Poll::Ready(None)` only when **every** constituent
/// stream has returned `Poll::Ready(None)`.
///
/// # Fused stream requirement
///
/// Streams must be fused after close: once a stream returns
/// `Poll::Ready(None)` it must keep returning `Poll::Ready(None)` on
/// subsequent polls. All bloxide runtime channel receivers satisfy this; a
/// non-fused stream will be polled again after closing.
///
/// # Blanket implementations
/// Generated at build time by bloxide-core's `build.rs` (via
/// `bloxide-codegen`, from the `[mailboxes]` section of `blox.toml`) into
/// `$OUT_DIR/mailboxes_impls.rs` for 1- through 16-element tuples of
/// `Stream`s where `E: From<stream::Item>` for each element.
pub trait Mailboxes<E: Send + 'static>: Send + 'static + Unpin {
    fn poll_next(&mut self, cx: &mut Context<'_>) -> Poll<Option<E>>;
}

// ── NoMailboxes ───────────────────────────────────────────────────────────────

/// A mailbox set that never produces an event.
///
/// Use as `type Mailboxes<R: BloxRuntime> = NoMailboxes` for `MachineSpec`
/// implementations that are driven directly via `machine.dispatch(event)`
/// rather than through a run loop (e.g., in unit tests).
///
/// # Warning — do not pair with `run()` + `RunConfig::unsupervised()`
///
/// `poll_next` always returns `Poll::Pending` and never registers a waker,
/// so the run loop has nothing that can wake it. Combined with
/// [`RunConfig::unsupervised()`](crate::runloop::RunConfig::unsupervised)
/// (auto-start, no lifecycle stream, no abort stream), `run()` auto-starts
/// the machine and then sleeps forever — the actor can never receive an
/// event, stop, or exit. `NoMailboxes` is only safe for non-runloop use
/// (direct `dispatch()`), or with `run()` when the config still provides a
/// lifecycle (or abort) stream to drive and eventually stop the actor.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct NoMailboxes;

impl<E: Send + 'static> Mailboxes<E> for NoMailboxes {
    fn poll_next(&mut self, _cx: &mut Context<'_>) -> Poll<Option<E>> {
        Poll::Pending
    }
}

// ── Tuple blanket impls (1-16) ────────────────────────────────────────────────
//
// Generated at build time by build.rs into `$OUT_DIR/mailboxes_impls.rs` and
// included from lib.rs. Each generated impl polls streams in priority order
// (index 0 first) and collects the first ready item.
// `Poll::Ready(None)` propagates as graceful shutdown.

// Tuple mailbox impls (1-16) are generated by bloxide-codegen at build time (see blox.toml).

#[cfg(all(test, feature = "std"))]
mod tests {
    use super::*;
    use core::pin::Pin;
    use futures_core::Stream;

    struct ClosedStream;
    impl Stream for ClosedStream {
        type Item = u32;
        fn poll_next(self: Pin<&mut Self>, _cx: &mut Context<'_>) -> Poll<Option<u32>> {
            Poll::Ready(None)
        }
    }

    struct PendingStream;
    impl Stream for PendingStream {
        type Item = u32;
        fn poll_next(self: Pin<&mut Self>, _cx: &mut Context<'_>) -> Poll<Option<u32>> {
            Poll::Pending
        }
    }

    struct YieldThenClose {
        yielded: bool,
    }
    impl Stream for YieldThenClose {
        type Item = u32;
        fn poll_next(self: Pin<&mut Self>, _cx: &mut Context<'_>) -> Poll<Option<u32>> {
            if !self.yielded {
                self.get_mut().yielded = true;
                Poll::Ready(Some(42))
            } else {
                Poll::Ready(None)
            }
        }
    }

    #[derive(Debug, Clone, Copy)]
    struct TestEvent(u32);

    impl From<u32> for TestEvent {
        fn from(v: u32) -> Self {
            TestEvent(v)
        }
    }

    #[test]
    fn mailbox_close_returns_ready_none() {
        // A single closed stream → poll_next should return Ready(None) immediately.
        let mut mailboxes: (ClosedStream,) = (ClosedStream,);
        let waker = futures_task_waker();
        let mut cx = Context::from_waker(&waker);
        let result = <(ClosedStream,) as Mailboxes<TestEvent>>::poll_next(&mut mailboxes, &mut cx);
        assert!(
            matches!(result, Poll::Ready(None)),
            "closed stream must produce Ready(None), got {:?}",
            result
        );
    }

    #[test]
    fn mailbox_close_in_pair_returns_ready_none() {
        // All-close semantics: when EVERY stream in the tuple is closed,
        // poll_next returns Ready(None) — graceful shutdown.
        let mut mailboxes: (ClosedStream, ClosedStream) = (ClosedStream, ClosedStream);
        let waker = futures_task_waker();
        let mut cx = Context::from_waker(&waker);
        let result = <(ClosedStream, ClosedStream) as Mailboxes<TestEvent>>::poll_next(
            &mut mailboxes,
            &mut cx,
        );
        assert!(
            matches!(result, Poll::Ready(None)),
            "all streams closed must produce Ready(None), got {:?}",
            result
        );
    }

    #[test]
    fn mailbox_pair_one_closed_one_pending_is_pending() {
        // All-close semantics (issue #134): a single closed stream does NOT
        // shut down the actor — the pair stays Pending while any stream is open.
        let mut mailboxes: (ClosedStream, PendingStream) = (ClosedStream, PendingStream);
        let waker = futures_task_waker();
        let mut cx = Context::from_waker(&waker);
        let result = <(ClosedStream, PendingStream) as Mailboxes<TestEvent>>::poll_next(
            &mut mailboxes,
            &mut cx,
        );
        assert!(
            matches!(result, Poll::Pending),
            "one closed + one open stream must be Pending, got {:?}",
            result
        );
    }

    #[test]
    fn mailbox_closed_stream_repoll_is_safe_and_stays_closed() {
        // Fused requirement: re-polling after close keeps returning Ready(None);
        // the pair must remain Pending while the other stream is open.
        let mut mailboxes: (ClosedStream, PendingStream) = (ClosedStream, PendingStream);
        let waker = futures_task_waker();
        let mut cx = Context::from_waker(&waker);
        for _ in 0..3 {
            let result = <(ClosedStream, PendingStream) as Mailboxes<TestEvent>>::poll_next(
                &mut mailboxes,
                &mut cx,
            );
            assert!(
                matches!(result, Poll::Pending),
                "re-poll after close must stay Pending, got {:?}",
                result
            );
        }
    }

    #[test]
    fn mailbox_item_from_later_stream_wins_over_earlier_closed() {
        // Priority: a ready item on a later stream is returned even though an
        // earlier stream is closed.
        let mut mailboxes: (ClosedStream, YieldThenClose) =
            (ClosedStream, YieldThenClose { yielded: false });
        let waker = futures_task_waker();
        let mut cx = Context::from_waker(&waker);
        let result = <(ClosedStream, YieldThenClose) as Mailboxes<TestEvent>>::poll_next(
            &mut mailboxes,
            &mut cx,
        );
        assert!(
            matches!(result, Poll::Ready(Some(TestEvent(42)))),
            "ready item must be returned over a closed earlier stream, got {:?}",
            result
        );
    }

    #[test]
    fn mailbox_yields_item_then_closes() {
        // First poll returns Ready(Some(event)), second returns Ready(None).
        let mut mailboxes: (YieldThenClose,) = (YieldThenClose { yielded: false },);
        let waker = futures_task_waker();
        let mut cx = Context::from_waker(&waker);

        let first = <(YieldThenClose,) as Mailboxes<TestEvent>>::poll_next(&mut mailboxes, &mut cx);
        assert!(
            matches!(first, Poll::Ready(Some(TestEvent(42)))),
            "first poll must yield the item, got {:?}",
            first
        );

        let second =
            <(YieldThenClose,) as Mailboxes<TestEvent>>::poll_next(&mut mailboxes, &mut cx);
        assert!(
            matches!(second, Poll::Ready(None)),
            "second poll after close must return Ready(None), got {:?}",
            second
        );
    }

    #[test]
    fn no_mailboxes_always_pending() {
        let mut mb = NoMailboxes;
        let waker = futures_task_waker();
        let mut cx = Context::from_waker(&waker);
        let result: Poll<Option<TestEvent>> = mb.poll_next(&mut cx);
        assert!(
            matches!(result, Poll::Pending),
            "NoMailboxes must always be Pending, got {:?}",
            result
        );
    }

    /// Create a no-op waker for polling in tests.
    fn futures_task_waker() -> std::task::Waker {
        use std::task::{RawWaker, RawWakerVTable, Waker};
        static VTABLE: RawWakerVTable = RawWakerVTable::new(
            |_| RawWaker::new(std::ptr::null(), &VTABLE),
            |_| {},
            |_| {},
            |_| {},
        );
        unsafe { Waker::from_raw(RawWaker::new(std::ptr::null(), &VTABLE)) }
    }
}
