// Copyright 2025 Bloxide, all rights reserved
//! Materialization of pure-TOML blox crates.
//!
//! A pure-TOML blox is a `blox.toml`-only source under a `bloxes/` directory
//! (see `util::BloxSourceKind::PureToml`). `cargo blox generate` materializes
//! a complete crate per blox into
//! `target/bloxide-generated/crates/<crate-name>/`:
//!
//! ```text
//! target/bloxide-generated/
//!   Cargo.toml                      ← generated workspace (members = ["crates/*", "examples/*"])
//!   crates/<crate-name>/
//!     Cargo.toml                    ← generated (deps derived from blox.toml)
//!     build.rs                      ← generated (re-syncs from the source blox.toml)
//!     src/lib.rs                    ← generated (no_std, prelude, consts)
//!     src/generated/*.rs            ← `generate_all` output
//!     tests/*.rs                    ← mirrored from <blox dir>/tests/
//! ```
//!
//! The crate name is the kebab-case actor name + `-blox` (`Ping` →
//! `ping-blox`). Dependencies are derived from the blox.toml sections
//! (message paths, context imports, spec imports, action crates) plus any
//! `[package.dependencies]` extras, and resolved as path dependencies via the
//! workspace root's `[workspace.dependencies]` table.
//!
//! Every write goes through `write_if_changed` so repeated `cargo blox
//! generate` runs (and the generated `build.rs` re-sync) are byte-identical
//! and mtime-stable.

use crate::schema::{BloxConfig, DepSpec, SystemConfig};
use crate::system_wiring::{extract_crates_from_path, rustfmt_source};
use crate::util;
use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};

/// Workspace-relative directory holding the generated blox-crate workspace.
pub const GENERATED_WORKSPACE_DIR: &str = "target/bloxide-generated";

const MANIFEST_HEADER: &str = "# Copyright 2025 Bloxide, all rights reserved\n\
     # Auto-generated by bloxide-codegen from blox.toml — do not edit by hand; regenerate with `cargo blox generate`.\n";

/// Header for the generated WORKSPACE root manifest (covers both blox crates
/// and example crates).
const WORKSPACE_MANIFEST_HEADER: &str = "# Copyright 2025 Bloxide, all rights reserved\n\
     # Auto-generated by bloxide-codegen from blox.toml / system.toml — do not edit by hand; regenerate with `cargo blox generate`.\n";

// ---------------------------------------------------------------------------
// Public entry points
// ---------------------------------------------------------------------------

/// Ensure the generated workspace root manifest
/// (`target/bloxide-generated/Cargo.toml`) exists. Called once per
/// `cargo blox generate` run when at least one pure-TOML blox or example
/// (system.toml) was found.
pub fn sync_generated_workspace(workspace_root: &Path) -> anyhow::Result<()> {
    let generated_root = workspace_root.join(GENERATED_WORKSPACE_DIR);
    let content = format!(
        "{}\n[workspace]\nmembers = [\"crates/*\", \"examples/*\"]\nresolver = \"2\"\n",
        WORKSPACE_MANIFEST_HEADER
    );
    let mut content = content;
    content.push_str("\n[profile.dev]\npanic = \"abort\"\n[profile.release]\npanic = \"abort\"\n");
    for (url, patches) in crate::packages::load(workspace_root)?.patches {
        content.push_str(&format!("\n[patch.\"{url}\"]\n"));
        for (name, source) in patches {
            content.push_str(&format!("{name} = {source}\n"));
        }
    }
    write_if_changed(&generated_root.join("Cargo.toml"), &content)
}

/// Repo-relative directories of the impl crates referenced by any
/// `system.toml` (`[[actors]] impl_crate`, plus `source = "factory"`
/// injection crates), resolved via the root `[workspace.dependencies]` table
/// — the same resolution the generated example manifests use. Names with no
/// path entry there are skipped (the example manifest generation reports
/// them as errors when truly required).
///
/// Impl crates path-depend into `target/bloxide-generated/`, so they are
/// excluded from the repo workspace (the root must load before the generated
/// tree exists). They also CANNOT be members of the generated workspace —
/// cargo requires members to be hierarchically below the workspace root.
/// They therefore build as path dependencies of the generated example
/// crates, and `cargo blox test` runs their tests explicitly via
/// `--manifest-path`.
pub fn impl_crate_dirs(workspace_root: &Path) -> Vec<String> {
    let Ok(ws_paths) = workspace_dep_paths(workspace_root) else {
        return Vec::new();
    };
    let mut names: BTreeSet<String> = BTreeSet::new();
    for entry in walkdir::WalkDir::new(workspace_root)
        .into_iter()
        .filter_entry(|e| e.file_name() != "target")
        .filter_map(|e| e.ok())
    {
        if entry.file_name() != "system.toml" {
            continue;
        }
        let Ok(content) = std::fs::read_to_string(entry.path()) else {
            continue;
        };
        let Ok(config) = toml::from_str::<SystemConfig>(&content) else {
            continue;
        };
        for actor in &config.actors {
            if let Some(impl_crate) = &actor.impl_crate {
                names.insert(impl_crate.replace('_', "-"));
            }
            for src in actor.inject.values() {
                if src.source == "factory" {
                    if let Some(crate_name) = &src.crate_name {
                        names.insert(crate_name.replace('_', "-"));
                    }
                }
            }
        }
    }
    names
        .into_iter()
        .filter_map(|name| ws_paths.get(&name).cloned())
        .collect()
}

/// Materialize (or re-sync) the crate for one pure-TOML blox.
///
/// - `blox_toml` — the source blox.toml (`<workspace>/bloxes/<name>/blox.toml`).
/// - `workspace_root` — the repository workspace root.
/// - `crate_dir` — `target/bloxide-generated/crates/<crate-name>`.
///
/// Returns the crate name. Idempotent: only files whose content changed are
/// rewritten.
pub fn sync_blox_crate(
    blox_toml: &Path,
    workspace_root: &Path,
    crate_dir: &Path,
) -> anyhow::Result<String> {
    let content = std::fs::read_to_string(blox_toml)?;
    let config: BloxConfig = toml::from_str(&content)?;
    let crate_name = util::pure_toml_crate_name(&config).ok_or_else(|| {
        anyhow::anyhow!(
            "pure-TOML blox {} has no [actor] section — cannot derive a crate name",
            blox_toml.display()
        )
    })?;

    // Normalize to absolute paths: callers pass anything from absolute paths
    // (cargo blox generate) to `../../../../` and `.` (the generated
    // build.rs, whose cwd is the crate dir). The crate dir is created first
    // so it can be canonicalized on a fresh bootstrap.
    std::fs::create_dir_all(crate_dir)?;
    let blox_toml = std::fs::canonicalize(blox_toml)?;
    let workspace_root = std::fs::canonicalize(workspace_root)?;
    let crate_dir = std::fs::canonicalize(crate_dir)?;

    // Cargo.toml
    let manifest = crate_manifest(&config, &crate_name, &workspace_root, &crate_dir)?;
    write_if_changed(&crate_dir.join("Cargo.toml"), &manifest)?;

    // build.rs (re-sync trigger for plain cargo builds)
    let build_rs = build_rs_source(&blox_toml, &workspace_root, &crate_dir)?;
    write_if_changed(&crate_dir.join("build.rs"), &build_rs)?;

    // src/generated/*.rs (existing generate_all output, rustfmt-formatted
    // exactly like `cargo blox generate`'s in-crate flow).
    let files = crate::generate_all(&config, &crate_name)?;
    let generated_dir = crate_dir.join("src").join("generated");
    std::fs::create_dir_all(&generated_dir)?;
    let mut fresh: BTreeSet<String> = BTreeSet::new();
    let mut uses_alloc = false;
    for (filename, raw) in &files {
        let formatted = rustfmt_source(raw)?;
        if formatted.contains("alloc::") {
            uses_alloc = true;
        }
        fresh.insert(filename.clone());
        write_if_changed(&generated_dir.join(filename), &formatted)?;
    }
    // The generated/ directory is fully owned — remove files that are no
    // longer emitted (e.g. after a section was deleted from the blox.toml).
    for entry in std::fs::read_dir(&generated_dir)?.flatten() {
        let name = entry.file_name().to_string_lossy().to_string();
        if name.ends_with(".rs") && !fresh.contains(&name) {
            std::fs::remove_file(entry.path())?;
        }
    }

    // src/lib.rs
    let lib = lib_rs_source(&config, uses_alloc)?;
    write_if_changed(&crate_dir.join("src").join("lib.rs"), &lib)?;

    // tests/ — mirror the source tests directory (if any).
    let source_tests = blox_toml.parent().unwrap().join("tests");
    sync_tests_dir(&source_tests, &crate_dir.join("tests"))?;

    Ok(crate_name)
}

/// Entry point used by the generated `build.rs`: re-sync the crate at
/// `crate_dir` from its source `blox_toml` (paths may be relative — build
/// scripts run with the package root as cwd).
pub fn sync_from_source(
    blox_toml: &Path,
    workspace_root: &Path,
    crate_dir: &Path,
) -> anyhow::Result<()> {
    crate::packages::verify(workspace_root)?;
    sync_blox_crate(blox_toml, workspace_root, crate_dir)?;
    Ok(())
}

// ---------------------------------------------------------------------------
// Dependency derivation
// ---------------------------------------------------------------------------

/// Crates referenced by a blox.toml that become `[dependencies]` of the
/// materialized crate. Underscored crate names (e.g. `bloxide_timer`).
pub(crate) fn referenced_crates(config: &BloxConfig) -> BTreeSet<String> {
    /// Import path prefixes that never name an external crate.
    const SKIP: [&str; 5] = ["crate", "core", "std", "alloc", "Self"];

    let mut crates = BTreeSet::new();
    // The generated code always references ::bloxide_core.
    crates.insert("bloxide_core".to_string());

    if let Some(event) = &config.event {
        for mailbox in &event.mailboxes {
            let path = mailbox.message_path.as_deref().unwrap_or(&mailbox.message);
            crates.extend(extract_crates_from_path(path));
        }
    }

    if let Some(ctx) = &config.context {
        for imp in ctx.imports.iter().chain(ctx.feature_imports.iter()) {
            if let Some(first) = imp.split("::").next() {
                if !SKIP.contains(&first) {
                    crates.insert(first.to_string());
                }
            }
        }
        // Context action crates provide the concrete action functions; the
        // blox crate links them so its `[features]` can forward to them and
        // downstream consumers see a complete dependency graph.
        for action in &ctx.actions {
            if !action.impl_required {
                if let Some(crate_name) = &action.crate_name {
                    crates.insert(crate_name.clone());
                }
            }
        }
    }

    if let Some(topology) = &config.topology {
        for imp in topology
            .spec_imports
            .iter()
            .chain(topology.feature_spec_imports.iter())
        {
            if let Some(first) = imp.split("::").next() {
                if !SKIP.contains(&first) {
                    crates.insert(first.to_string());
                }
            }
        }
    }

    crates
}

/// Feature names referenced by `feature = "..."` gates anywhere in the
/// blox.toml. Each must exist in the materialized crate's `[features]` table
/// or rustc's check-cfg rejects the generated `#[cfg(feature = ...)]` code.
fn referenced_features(config: &BloxConfig) -> BTreeSet<String> {
    let mut feats = BTreeSet::new();
    if let Some(ctx) = &config.context {
        feats.extend(ctx.feature.iter().cloned());
        for u in &ctx.uses {
            feats.extend(u.feature.iter().cloned());
            for f in &u.fields {
                feats.extend(f.feature.iter().cloned());
            }
        }
        for a in &ctx.actions {
            feats.extend(a.feature.iter().cloned());
        }
    }
    if let Some(event) = &config.event {
        feats.extend(event.feature.iter().cloned());
        for m in &event.mailboxes {
            feats.extend(m.feature.iter().cloned());
        }
    }
    if let Some(topology) = &config.topology {
        for t in &topology.transitions {
            feats.extend(t.feature.iter().cloned());
        }
        for ee in topology.entry.iter().chain(topology.exit.iter()) {
            feats.extend(ee.feature.iter().cloned());
        }
    }
    feats
}

/// The `[features]` table for the materialized crate.
///
/// `[package.features]` in blox.toml wins verbatim when present. Otherwise a
/// default is synthesized: `default = ["std"]`, `std = ["bloxide-core/std"]`,
/// plus an empty feature for every feature gate referenced in the TOML
/// (e.g. `dynamic = []`).
fn crate_features(config: &BloxConfig) -> anyhow::Result<BTreeMap<String, Vec<String>>> {
    let referenced = referenced_features(config);
    let declared = config
        .package
        .as_ref()
        .map(|p| p.features.clone())
        .unwrap_or_default();

    if !declared.is_empty() {
        let missing: Vec<String> = referenced
            .iter()
            .filter(|f| !declared.contains_key(*f))
            .cloned()
            .collect();
        if !missing.is_empty() {
            anyhow::bail!(
                "blox.toml gates code on feature(s) {} but [package.features] does not declare them",
                missing
                    .iter()
                    .map(|f| format!("\"{}\"", f))
                    .collect::<Vec<_>>()
                    .join(", ")
            );
        }
        return Ok(declared);
    }

    let mut features = BTreeMap::new();
    features.insert("default".to_string(), vec!["std".to_string()]);
    features.insert("std".to_string(), vec!["bloxide-core/std".to_string()]);
    for feat in referenced {
        features.entry(feat).or_default();
    }
    Ok(features)
}

/// Parse the workspace root Cargo.toml's `[workspace.dependencies]` table:
/// crate name → workspace-relative path.
pub(crate) fn workspace_dep_paths(
    workspace_root: &Path,
) -> anyhow::Result<BTreeMap<String, String>> {
    let content = std::fs::read_to_string(workspace_root.join("Cargo.toml"))?;
    let parsed: toml::Value = toml::from_str(&content)?;
    let mut map = BTreeMap::new();
    if let Some(deps) = parsed
        .get("workspace")
        .and_then(|w| w.get("dependencies"))
        .and_then(|d| d.as_table())
    {
        for (name, value) in deps {
            if let Some(path) = value.get("path").and_then(|p| p.as_str()) {
                map.insert(name.clone(), path.to_string());
            }
        }
    }
    Ok(map)
}

/// Parse the workspace root Cargo.toml's `[workspace.package]` values used by
/// the materialized crate manifest (version, edition, license).
pub(crate) fn workspace_package_values(workspace_root: &Path) -> (String, String, Option<String>) {
    let fallback = || ("0.0.0".to_string(), "2021".to_string(), None);
    let Ok(content) = std::fs::read_to_string(workspace_root.join("Cargo.toml")) else {
        return fallback();
    };
    let Ok(parsed) = toml::from_str::<toml::Value>(&content) else {
        return fallback();
    };
    let Some(pkg) = parsed.get("workspace").and_then(|w| w.get("package")) else {
        return fallback();
    };
    let get_str = |key: &str| pkg.get(key).and_then(|v| v.as_str()).map(String::from);
    (
        get_str("version").unwrap_or_else(|| "0.0.0".to_string()),
        get_str("edition").unwrap_or_else(|| "2021".to_string()),
        get_str("license"),
    )
}

// ---------------------------------------------------------------------------
// Emission (pure string builders — unit-testable)
// ---------------------------------------------------------------------------

/// Render the materialized crate's `Cargo.toml`.
pub fn crate_manifest(
    config: &BloxConfig,
    crate_name: &str,
    workspace_root: &Path,
    crate_dir: &Path,
) -> anyhow::Result<String> {
    let composition = crate::packages::load(workspace_root)?;
    let (version, edition, license) = composition
        .blox_metadata
        .get(crate_name)
        .cloned()
        .unwrap_or_else(|| workspace_package_values(workspace_root));
    let prefix = relative_prefix(workspace_root, crate_dir)?;

    let mut out = String::new();
    out.push_str(MANIFEST_HEADER);
    out.push('\n');
    out.push_str("[package]\n");
    out.push_str(&format!("name = \"{}\"\n", crate_name));
    out.push_str(&format!("version = \"{}\"\n", version));
    out.push_str(&format!("edition = \"{}\"\n", edition));
    if let Some(license) = &license {
        out.push_str(&format!("license = \"{}\"\n", license));
    }
    out.push_str("publish = false\n");
    if let Some(desc) = config.package.as_ref().and_then(|p| p.description.as_ref()) {
        out.push_str(&format!("description = \"{}\"\n", desc));
    }
    out.push('\n');

    // [features]
    let features = crate_features(config)?;
    out.push_str("[features]\n");
    for (name, values) in &features {
        out.push_str(&format!("{} = {}\n", name, toml_string_list(values)));
    }
    out.push('\n');

    // [dependencies] — derived + declared extras, sorted by cargo name.
    let mut deps = BTreeMap::new();
    for name in referenced_crates(config) {
        deps.insert(name.replace('_', "-"), DepSpec::default());
    }
    if let Some(pkg) = &config.package {
        deps.extend(pkg.dependencies.clone());
    }
    out.push_str("[dependencies]\n");
    for (name, spec) in &deps {
        out.push_str(&crate::packages::dependency_line(
            workspace_root,
            &prefix,
            name,
            &spec.features,
            true,
        )?);
    }
    out.push('\n');
    if let Some(pkg) = &config.package {
        if !pkg.dev_dependencies.is_empty() {
            out.push_str("[dev-dependencies]\n");
            for (name, spec) in &pkg.dev_dependencies {
                out.push_str(&crate::packages::dependency_line(
                    workspace_root,
                    &prefix,
                    name,
                    &spec.features,
                    false,
                )?);
            }
            out.push('\n');
        }
    }
    out.push_str("[build-dependencies]\n");
    out.push_str(&crate::packages::dependency_line(
        workspace_root,
        &prefix,
        "bloxide-codegen",
        &[],
        false,
    )?);

    Ok(out)
}

/// Render the materialized crate's `src/lib.rs`.
///
/// `uses_alloc` should be true when any generated source references `alloc::`
/// (the caller scans the `generate_all` output) — the `extern crate alloc;`
/// line is emitted only then.
pub fn lib_rs_source(config: &BloxConfig, uses_alloc: bool) -> anyhow::Result<String> {
    let actor_name = config
        .actor
        .as_ref()
        .map(|a| a.name.as_str())
        .unwrap_or("Unknown");
    let description = config
        .package
        .as_ref()
        .and_then(|p| p.description.clone())
        .unwrap_or_else(|| format!("{} actor blox — runtime-agnostic.", actor_name));

    // Re-export list: <Actor>Ctx / <Actor>Event / <Actor>Spec / <Actor>State,
    // from whichever sections exist.
    let mut exports: Vec<String> = Vec::new();
    if let Some(ctx) = &config.context {
        exports.push(ctx.name.clone());
    }
    if let Some(event) = &config.event {
        exports.push(event.name.clone());
    }
    if config.actor.is_some() {
        exports.push(format!("{}Spec", actor_name));
        exports.push(format!("{}State", actor_name));
    }
    let export_list = exports.join(", ");

    let features = crate_features(config)?;

    let mut out = String::new();
    out.push_str("// Copyright 2025 Bloxide, all rights reserved\n");
    out.push_str("// Auto-generated by bloxide-codegen from blox.toml — do not edit by hand; regenerate with `cargo blox generate`.\n");
    out.push_str(&format!("//! {}\n", description));
    out.push_str("#![no_std]\n");
    if uses_alloc {
        out.push_str("extern crate alloc;\n");
    }
    out.push('\n');
    if features.contains_key("std") {
        out.push_str("#[cfg(feature = \"std\")]\nextern crate std;\n\n");
    }
    out.push_str("pub mod generated;\n\n");
    if !exports.is_empty() {
        out.push_str("/// Convenience re-exports for wiring sites.\n");
        out.push_str("pub mod prelude {\n");
        out.push_str(&format!("    pub use crate::{{{}}};\n", export_list));
        out.push_str("}\n\n");
        out.push_str(&format!("pub use generated::{{{}}};\n", export_list));
    }
    for c in &config.consts {
        out.push('\n');
        if let Some(doc) = &c.doc {
            out.push_str(&format!("/// {}\n", doc));
        }
        out.push_str(&format!("pub const {}: {} = {};\n", c.name, c.ty, c.value));
    }
    Ok(out)
}

/// Render the materialized crate's `build.rs`. Paths are relative to the
/// crate dir (build scripts run with the package root as cwd), keeping the
/// generated tree relocatable.
pub fn build_rs_source(
    blox_toml: &Path,
    workspace_root: &Path,
    crate_dir: &Path,
) -> anyhow::Result<String> {
    let prefix = relative_prefix(workspace_root, crate_dir)?;
    let blox_path = relative_path(crate_dir, blox_toml)?;
    let source_dir = relative_path(crate_dir, blox_toml.parent().unwrap())?;

    Ok(format!(
        "// Copyright 2025 Bloxide, all rights reserved\n\
         // Auto-generated by bloxide-codegen — do not edit by hand; regenerate with `cargo blox generate`.\n\
         //! Build script: keeps this materialized crate in sync with its source\n\
         //! blox.toml after the initial `cargo blox generate`. Regenerates\n\
         //! `src/generated/`, `src/lib.rs`, and `Cargo.toml`, and re-copies `tests/`,\n\
         //! whenever the source blox.toml or tests directory changes — plain\n\
         //! `cargo build` / `cargo test` stay fresh without re-running `cargo blox generate`.\n\
         //!\n\
         //! Note: a brand-new test file added to the source tests/ directory is\n\
         //! copied here on the next build, but cargo may need one extra invocation\n\
         //! to discover the new test target.\n\
         \n\
         fn main() {{\n\
         \x20   let blox_toml = \"{blox_path}\";\n\
         \x20   let tests_dir = \"{source_dir}/tests\";\n\
         \x20   println!(\"cargo:rerun-if-changed={{}}\", blox_toml);\n\
         \x20   if std::path::Path::new(tests_dir).is_dir() {{\n\
         \x20       println!(\"cargo:rerun-if-changed={{}}\", tests_dir);\n\
         \x20       for entry in std::fs::read_dir(tests_dir).into_iter().flatten().flatten() {{\n\
         \x20           let path = entry.path();\n\
         \x20           if path.extension().is_some_and(|ext| ext == \"rs\") {{\n\
         \x20               println!(\"cargo:rerun-if-changed={{}}\", path.display());\n\
         \x20           }}\n\
         \x20       }}\n\
         \x20   }}\n\
         \x20   bloxide_codegen::blox_crate::sync_from_source(\n\
         \x20       std::path::Path::new(blox_toml),\n\
         \x20       std::path::Path::new(\"{prefix}\"),\n\
         \x20       std::path::Path::new(\".\"),\n\
         \x20   )\n\
         \x20   .expect(\"failed to regenerate blox crate from blox.toml\");\n\
         }}\n"
    ))
}

// ---------------------------------------------------------------------------
// Internals
// ---------------------------------------------------------------------------

/// Relative prefix from `crate_dir` back up to `workspace_root`
/// (e.g. `"../../../../"` for `target/bloxide-generated/crates/<name>`).
pub fn relative_prefix(workspace_root: &Path, crate_dir: &Path) -> anyhow::Result<String> {
    let rel = crate_dir.strip_prefix(workspace_root).map_err(|_| {
        anyhow::anyhow!(
            "crate dir {} is not under the workspace root {}",
            crate_dir.display(),
            workspace_root.display()
        )
    })?;
    Ok("../".repeat(rel.components().count()))
}

/// `["a", "b"]` TOML array literal.
fn toml_string_list(items: &[String]) -> String {
    let inner = items
        .iter()
        .map(|i| format!("\"{}\"", i))
        .collect::<Vec<_>>()
        .join(", ");
    format!("[{}]", inner)
}

/// Write `content` to `path` only when it differs (preserves mtime → cargo
/// caching and idempotent `cargo blox generate`). Creates parent dirs.
pub(crate) fn write_if_changed(path: &Path, content: &str) -> anyhow::Result<()> {
    let needs_write = if path.exists() {
        std::fs::read_to_string(path)? != content
    } else {
        true
    };
    if needs_write {
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(path, content)?;
    }
    Ok(())
}

/// Mirror `*.rs` files from `source_dir` into `target_dir` (both may not
/// exist). The target directory is fully owned: files that disappeared from
/// the source are removed, and the target directory itself is removed when
/// the source has no tests.
pub(crate) fn sync_tests_dir(source_dir: &Path, target_dir: &Path) -> anyhow::Result<()> {
    let mut sources: BTreeMap<String, PathBuf> = BTreeMap::new();
    if source_dir.is_dir() {
        for entry in std::fs::read_dir(source_dir)?.flatten() {
            let path = entry.path();
            if path.extension().is_some_and(|ext| ext == "rs") {
                sources.insert(entry.file_name().to_string_lossy().to_string(), path);
            }
        }
    }

    if sources.is_empty() {
        if target_dir.is_dir() {
            std::fs::remove_dir_all(target_dir)?;
        }
        return Ok(());
    }

    std::fs::create_dir_all(target_dir)?;
    for (name, src) in &sources {
        let content = std::fs::read_to_string(src)?;
        write_if_changed(&target_dir.join(name), &content)?;
    }
    for entry in std::fs::read_dir(target_dir)?.flatten() {
        let name = entry.file_name().to_string_lossy().to_string();
        if name.ends_with(".rs") && !sources.contains_key(&name) {
            std::fs::remove_file(entry.path())?;
        }
    }
    Ok(())
}

/// Relative path between canonical absolute paths, including external sources.
pub fn relative_path(from: &Path, to: &Path) -> anyhow::Result<String> {
    fn absolute(path: &Path) -> anyhow::Result<PathBuf> {
        let path = if path.is_absolute() {
            path.to_path_buf()
        } else {
            std::env::current_dir()?.join(path)
        };
        let mut normalized = PathBuf::new();
        for component in path.components() {
            if component == std::path::Component::ParentDir {
                normalized.pop();
            } else if component != std::path::Component::CurDir {
                normalized.push(component.as_os_str());
            }
        }
        Ok(normalized)
    }
    let a = absolute(from)?;
    let b = absolute(to)?;
    let a: Vec<_> = a.components().collect();
    let b: Vec<_> = b.components().collect();
    let common = a.iter().zip(&b).take_while(|(a, b)| a == b).count();
    let mut result = PathBuf::new();
    for _ in common..a.len() {
        result.push("..");
    }
    for component in &b[common..] {
        result.push(component.as_os_str());
    }
    Ok(result.display().to_string())
}
