// Copyright 2025 Bloxide, all rights reserved
//! Materialization of pure-TOML example crates (system.toml sources).
//!
//! An example is a `system.toml`-only source under `examples/<name>/` (plus
//! an optional `tests/` directory). `cargo blox generate` materializes a
//! complete crate per example into
//! `target/bloxide-generated/examples/<crate-name>/`:
//!
//! ```text
//! target/bloxide-generated/
//!   Cargo.toml                       ← generated workspace (members = ["crates/*", "examples/*"])
//!   examples/<crate-name>/
//!     Cargo.toml                     ← generated (deps derived from system.toml + blox.tomls)
//!     build.rs                       ← generated (re-syncs from the source system.toml)
//!     src/main.rs                    ← system wiring (the binary)
//!     src/lib.rs                     ← generated (`pub mod generated;` for tests)
//!     src/generated/*_spec_skeleton.rs + mod.rs  ← concrete specs
//!     tests/*.rs                     ← mirrored from examples/<name>/tests/
//! ```
//!
//! The crate name is `[system] name` (falling back to the source directory
//! name), so existing test imports like `tokio_pool_demo::generated::...`
//! keep working.
//!
//! The example crate is a member of the GENERATED workspace, not the repo
//! workspace, so `{ workspace = true }` cannot resolve: every repo crate
//! (blox crates, messages, context, impl, runtime, supervisor, spawn)
//! becomes a path dependency — into `../..//crates/` for materialized blox
//! crates, and relative paths like `../../../../crates/...` for repo crates
//! (resolved via the workspace root's `[workspace.dependencies]` table, same
//! as [`crate::blox_crate`]). External deps (tokio, tracing, …) get explicit
//! versions copied from the root `[workspace.dependencies]` entries. Embassy
//! deps keep their inline-version behavior.
//!
//! Dev-dependencies: integration tests import crates directly (e.g.
//! `pool_blox::PoolCtx`). The crates a test may import are DERIVED FROM THE
//! TEST SOURCES: every lowercase `ident::` path prefix in `tests/*.rs` is a
//! crate candidate (skipping `std`/`core`/`alloc`/`crate`/`self`/`super`/
//! `generated` and the example crate itself); candidates that resolve via
//! the root `[workspace.dependencies]` or the discovered bloxes become
//! `[dev-dependencies]` entries, resolved exactly like regular dependencies.
//! Candidates matching no known crate are lowercase module segments of
//! multi-segment paths (e.g. `lifecycle` in `bloxide_core::lifecycle::…`)
//! and are dropped. Feature lists are copied from the `[dependencies]`
//! entry when the crate appears there.
//!
//! Every write goes through `write_if_changed` so repeated `cargo blox
//! generate` runs (and the generated `build.rs` re-sync) are byte-identical
//! and mtime-stable.

use crate::blox_crate::{
    relative_prefix, sync_tests_dir, workspace_dep_paths, workspace_package_values,
    write_if_changed, GENERATED_WORKSPACE_DIR,
};
use crate::schema::{BloxConfig, SystemConfig};
use crate::system_wiring::{extract_crates_from_path, rustfmt_source};
use crate::util;
use std::collections::{BTreeMap, BTreeSet};
use std::path::Path;

const MANIFEST_HEADER: &str = "# Copyright 2025 Bloxide, all rights reserved\n\
     # Auto-generated by bloxide-codegen from system.toml — do not edit by hand; regenerate with `cargo blox generate`.\n";

/// Identifiers that look like crate prefixes in test sources but are not.
const SCAN_SKIP: [&str; 7] = [
    "std",
    "core",
    "alloc",
    "crate",
    "self",
    "super",
    "generated",
];

// ---------------------------------------------------------------------------
// Public entry points
// ---------------------------------------------------------------------------

/// Derive the example crate name: `[system] name`, falling back to the
/// source directory name.
pub fn example_crate_name(config: &SystemConfig, system_toml: &Path) -> String {
    config.system.name.clone().unwrap_or_else(|| {
        system_toml
            .parent()
            .and_then(|d| d.file_name())
            .and_then(|n| n.to_str())
            .unwrap_or("bloxide-example")
            .to_string()
    })
}

/// Materialize (or re-sync) the example crate for one `system.toml`,
/// computing the target directory
/// (`target/bloxide-generated/examples/<crate-name>`) from the manifest.
/// Returns the crate name.
pub fn sync_example(system_toml: &Path, workspace_root: &Path) -> anyhow::Result<String> {
    let content = std::fs::read_to_string(system_toml)?;
    let mut config: SystemConfig = toml::from_str(&content)?;
    crate::packages::normalize(&mut config, workspace_root)?;
    let crate_name = example_crate_name(&config, system_toml);
    let example_dir = workspace_root
        .join(GENERATED_WORKSPACE_DIR)
        .join("examples")
        .join(&crate_name);
    sync_example_crate(system_toml, workspace_root, &example_dir)
}

/// Materialize (or re-sync) the crate for one example `system.toml`.
///
/// - `system_toml` — the source manifest (`<workspace>/examples/<name>/system.toml`).
/// - `workspace_root` — the repository workspace root.
/// - `example_dir` — `target/bloxide-generated/examples/<crate-name>`.
///
/// Returns the crate name. Idempotent: only files whose content changed are
/// rewritten.
pub fn sync_example_crate(
    system_toml: &Path,
    workspace_root: &Path,
    example_dir: &Path,
) -> anyhow::Result<String> {
    let content = std::fs::read_to_string(system_toml)?;
    let mut config: SystemConfig = toml::from_str(&content)?;
    crate::packages::normalize(&mut config, workspace_root)?;
    let crate_name = example_crate_name(&config, system_toml);

    // Normalize to absolute paths (see blox_crate::sync_blox_crate): the
    // example dir is created first so it can be canonicalized on a fresh
    // bootstrap.
    std::fs::create_dir_all(example_dir)?;
    let system_toml = std::fs::canonicalize(system_toml)?;
    let workspace_root = std::fs::canonicalize(workspace_root)?;
    let example_dir = std::fs::canonicalize(example_dir)?;

    // Blox configs (message/context dep derivation) + source kinds
    // (pure-TOML bloxes become path deps into ../..//crates/).
    let discovered = util::discover_bloxes(&workspace_root)?;
    let blox_configs: BTreeMap<String, BloxConfig> = discovered
        .iter()
        .map(|(k, v)| (k.clone(), v.config.clone()))
        .collect();

    // Crates the integration tests import directly (dev-dependencies).
    let source_tests = system_toml.parent().unwrap().join("tests");
    let dev_crates = test_imported_crates(&source_tests);

    // Cargo.toml
    let manifest = example_manifest(
        &config,
        &crate_name,
        &discovered,
        &blox_configs,
        &workspace_root,
        &example_dir,
        &dev_crates,
    )?;
    write_if_changed(&example_dir.join("Cargo.toml"), &manifest)?;
    if config.system.profile == "embedded" {
        write_if_changed(&workspace_root.join(GENERATED_WORKSPACE_DIR).join(".cargo/config.toml"),
            "# Generated Cortex-M entrypoint link configuration\n[target.thumbv8m.main-none-eabi]\nrustflags = [\"-C\", \"link-arg=-Tlink.x\"]\n")?;
    }

    // build.rs (re-sync trigger for plain cargo builds)
    let build_rs = build_rs_source(&system_toml, &workspace_root, &example_dir)?;
    write_if_changed(&example_dir.join("build.rs"), &build_rs)?;

    // src/main.rs (system wiring — already rustfmt'd by system_wiring::generate)
    let active_features = crate::infer_active_features(&config, &blox_configs);
    let main_rs = crate::system_wiring::generate(&config, &blox_configs, &active_features)?;
    write_if_changed(&example_dir.join("src").join("main.rs"), &main_rs)?;

    // src/generated/*_spec_skeleton.rs + mod.rs (concrete specs)
    sync_generated_specs(&config, &blox_configs, &example_dir)?;

    // src/lib.rs (uniform library target so tests can import the crate)
    let mut lib = lib_rs_source(&crate_name);
    if !example_dir.join("src/generated/mod.rs").exists() {
        lib = lib.replace("pub mod generated;", "");
    }
    if config.system.profile == "embedded" {
        lib = format!("#![no_std]\n{lib}");
    }
    write_if_changed(&example_dir.join("src").join("lib.rs"), &lib)?;

    // tests/ — mirror the source tests directory (if any).
    sync_tests_dir(&source_tests, &example_dir.join("tests"))?;

    Ok(crate_name)
}

/// Entry point used by the generated `build.rs`: re-sync the crate at
/// `example_dir` from its source `system_toml` (paths may be relative —
/// build scripts run with the package root as cwd).
pub fn sync_from_source(
    system_toml: &Path,
    workspace_root: &Path,
    example_dir: &Path,
) -> anyhow::Result<()> {
    crate::packages::verify(workspace_root)?;
    sync_example_crate(system_toml, workspace_root, example_dir)?;
    Ok(())
}

// ---------------------------------------------------------------------------
// Concrete specs (src/generated/)
// ---------------------------------------------------------------------------

/// Generate the concrete `*_spec_skeleton.rs` files (actors + supervisors)
/// and the `mod.rs` declaring them. The `src/generated/` directory is fully
/// owned: files no longer emitted are removed.
fn sync_generated_specs(
    config: &SystemConfig,
    blox_configs: &BTreeMap<String, BloxConfig>,
    example_dir: &Path,
) -> anyhow::Result<()> {
    // Collect all spec files: actors + supervisors
    let mut all_spec_files = Vec::new();

    if !config.actors.is_empty() {
        let spec_files =
            crate::system_spec::generate_concrete_spec_files(blox_configs, &config.actors)?;
        all_spec_files.extend(spec_files);
    }

    // Concrete specs for supervisors referenced in [[supervision]]
    for sup in &config.supervision {
        let supervisor_crate = &sup.supervisor;
        if let Some(blox_config) = blox_configs.get(supervisor_crate) {
            let blox_crate_path = format!("::{}", supervisor_crate.replace('-', "_"));
            let code = crate::system_spec::generate_concrete_spec_skeleton(
                blox_config,
                None, // supervisors don't have impl_crate
                supervisor_crate,
                &blox_crate_path,
                None, // no active feature for supervisor
            )?;
            all_spec_files.push((supervisor_crate.replace('-', "_").to_lowercase(), code));
        }
    }

    let generated_dir = example_dir.join("src").join("generated");
    if all_spec_files.is_empty() {
        if generated_dir.is_dir() {
            std::fs::remove_dir_all(&generated_dir)?;
        }
        return Ok(());
    }

    std::fs::create_dir_all(&generated_dir)?;
    let mut mod_content = String::from(
        "// Copyright 2025 Bloxide, all rights reserved\n\
         // Auto-generated module. Do not edit manually.\n\
         //! Generated by bloxide-codegen from system.toml — do not edit by hand; regenerate with `cargo blox generate`.\n",
    );
    let mut fresh: BTreeSet<String> = BTreeSet::new();
    for (actor_name, spec_code) in &all_spec_files {
        let module_name = actor_name.replace('-', "_").to_lowercase() + "_spec_skeleton";
        let filename = format!("{}.rs", module_name);
        // Format before writing so `cargo fmt --check` passes on generated
        // files and re-generation is byte-identical (idempotent).
        let spec_code = rustfmt_source(spec_code)?;
        fresh.insert(filename.clone());
        write_if_changed(&generated_dir.join(&filename), &spec_code)?;
        mod_content.push_str(&format!("pub mod {};\n", module_name));
        mod_content.push_str(&format!(
            "#[allow(unused_imports)]\npub use {}::*;\n",
            module_name
        ));
    }
    fresh.insert("mod.rs".to_string());
    write_if_changed(&generated_dir.join("mod.rs"), &mod_content)?;

    // The generated/ directory is fully owned — remove stale files.
    for entry in std::fs::read_dir(&generated_dir)?.flatten() {
        let name = entry.file_name().to_string_lossy().to_string();
        if name.ends_with(".rs") && !fresh.contains(&name) {
            std::fs::remove_file(entry.path())?;
        }
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// Test-source crate scan (dev-dependencies derivation)
// ---------------------------------------------------------------------------

/// Crates referenced by the example's `tests/*.rs` sources: every lowercase
/// `ident::` path prefix is treated as a crate name (underscored), skipping
/// std/core/alloc/crate/self/super/generated. The example crate itself is
/// filtered out by the caller's manifest builder.
pub fn test_imported_crates(tests_dir: &Path) -> BTreeSet<String> {
    let mut crates = BTreeSet::new();
    if !tests_dir.is_dir() {
        return crates;
    }
    for entry in std::fs::read_dir(tests_dir).into_iter().flatten().flatten() {
        let path = entry.path();
        if path.extension().is_some_and(|ext| ext == "rs") {
            if let Ok(content) = std::fs::read_to_string(&path) {
                scan_crate_prefixes(&content, &mut crates);
            }
        }
    }
    crates
}

/// Scan Rust source for `<ident>::` path prefixes where `ident` is an
/// all-lowercase snake_case segment (Rust crate names in paths are
/// lowercase; types are UpperCamel and are ignored).
fn scan_crate_prefixes(content: &str, out: &mut BTreeSet<String>) {
    let bytes = content.as_bytes();
    let is_ident = |b: u8| b.is_ascii_alphanumeric() || b == b'_';
    let mut i = 0;
    while i < bytes.len() {
        if (bytes[i].is_ascii_lowercase() || bytes[i] == b'_')
            && (i == 0 || !is_ident(bytes[i - 1]))
        {
            let start = i;
            while i < bytes.len() && is_ident(bytes[i]) {
                i += 1;
            }
            let ident = &content[start..i];
            if i + 1 < bytes.len()
                && bytes[i] == b':'
                && bytes[i + 1] == b':'
                && !SCAN_SKIP.contains(&ident)
            {
                out.insert(ident.to_string());
            }
        } else {
            i += 1;
        }
    }
}

// ---------------------------------------------------------------------------
// Dependency derivation + manifest emission
// ---------------------------------------------------------------------------

/// How a dependency is referenced from the example's Cargo.toml.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
enum DepKind {
    /// Repo crate or external crate: resolved via the workspace root's
    /// `[workspace.dependencies]` (path entry → path dep; version entry →
    /// explicit version copied verbatim).
    Resolved,
    /// Inline version spec (embassy crates — NOT workspace deps).
    InlineVersion,
    /// Pure-TOML blox: path dependency into target/bloxide-generated/crates.
    GeneratedBlox,
}

/// Collect the `[dependencies]` of the example crate.
///
/// Each entry is (crate_name, features, kind), sorted by name. This mirrors
/// the derivation the app-level Cargo.toml generation used: always-required
/// framework crates, runtime-specific crates, per-actor blox/message/
/// context/impl crates, and factory-injection crates.
fn collect_dependencies(
    config: &SystemConfig,
    discovered: &BTreeMap<String, util::DiscoveredBlox>,
    blox_configs: &BTreeMap<String, BloxConfig>,
) -> anyhow::Result<BTreeMap<String, (Vec<String>, DepKind)>> {
    let active_features = crate::infer_active_features(config, blox_configs);
    let mut deps: BTreeMap<String, (Vec<String>, DepKind)> = BTreeMap::new();
    let embedded = config.system.profile == "embedded";
    let std_features = if embedded {
        vec![]
    } else {
        vec!["std".to_string()]
    };

    // ── Always-required deps ───────────────────────────────────────────────
    deps.insert(
        "bloxide-core".to_string(),
        (std_features.clone(), DepKind::Resolved),
    );
    if !embedded {
        deps.insert(
            "bloxide-log".to_string(),
            (vec!["log".to_string()], DepKind::Resolved),
        );
    }
    deps.insert(
        "bloxide-supervisor".to_string(),
        (std_features.clone(), DepKind::Resolved),
    );
    // The system-level generated supervisor spec imports types from
    // bloxide-child-management (ChildGroup, ChildCtrl), so it must be
    // a dependency of every example that uses the supervisor.
    deps.insert(
        "bloxide-child-management".to_string(),
        (std_features.clone(), DepKind::Resolved),
    );

    // ── Runtime-specific deps ──────────────────────────────────────────────
    match config.system.runtime.as_str() {
        "tokio" => {
            deps.insert("bloxide-tokio".to_string(), (vec![], DepKind::Resolved));
            deps.insert("tokio".to_string(), (vec![], DepKind::Resolved));
            deps.insert("tracing".to_string(), (vec![], DepKind::Resolved));
            deps.insert(
                "tracing-subscriber".to_string(),
                (vec![], DepKind::Resolved),
            );
            deps.insert("tracing-log".to_string(), (vec![], DepKind::Resolved));
        }
        "embassy" => {
            deps.insert(
                "bloxide-embassy".to_string(),
                (std_features.clone(), DepKind::Resolved),
            );
            // embassy crates are NOT workspace deps — inline version specs.
            deps.insert(
                "embassy-executor".to_string(),
                (
                    {
                        let mut features = vec![
                            if embedded {
                                "arch-cortex-m".into()
                            } else {
                                "arch-std".into()
                            },
                            "executor-thread".into(),
                        ];
                        features.extend(config.system.executor_features.clone());
                        features
                    },
                    DepKind::InlineVersion,
                ),
            );
            deps.insert("embassy-sync".to_string(), (vec![], DepKind::InlineVersion));
            deps.insert(
                "embassy-time".to_string(),
                (
                    {
                        let mut features = if embedded {
                            vec![]
                        } else {
                            vec!["std".into(), "generic-queue-8".into()]
                        };
                        features.extend(config.system.time_features.clone());
                        features
                    },
                    DepKind::InlineVersion,
                ),
            );
            deps.insert(
                "critical-section".to_string(),
                (std_features.clone(), DepKind::InlineVersion),
            );
            deps.insert("static_cell".to_string(), (vec![], DepKind::Resolved));
            if !embedded {
                deps.insert("tracing".to_string(), (vec![], DepKind::Resolved));
                deps.insert(
                    "tracing-subscriber".to_string(),
                    (vec![], DepKind::Resolved),
                );
            }
            if embedded {
                deps.insert("cortex-m-rt".into(), (vec![], DepKind::InlineVersion));
            }
        }
        "test" => {
            // Test runtime — minimal deps.
        }
        other => {
            eprintln!("bloxide: warning: unknown runtime '{}'", other);
        }
    }

    if config.supervision.is_empty() {
        deps.remove("bloxide-supervisor");
        deps.remove("bloxide-child-management");
    }
    if let Some(platform) = &config.platform {
        deps.insert(
            platform.impl_crate.replace('_', "-"),
            (vec![], DepKind::Resolved),
        );
    }
    for service in &config.services {
        deps.insert(
            service.impl_crate.replace('_', "-"),
            (vec![], DepKind::Resolved),
        );
        if let Some(path) = &service.message_path {
            for name in extract_crates_from_path(path) {
                deps.entry(name.replace('_', "-"))
                    .or_insert((vec![], DepKind::Resolved));
            }
        }
    }
    // ── Per-actor deps ─────────────────────────────────────────────────────
    for actor in &config.actors {
        let is_timer = actor.kind.as_deref() == Some("timer");

        // The blox crate itself. Pure-TOML bloxes (discovered under a
        // `bloxes/` directory) are materialized into target/bloxide-generated
        // and referenced by path; everything else resolves via the workspace.
        let blox_name = &actor.blox;
        let features = active_features
            .get(blox_name)
            .cloned()
            .unwrap_or_default()
            .into_iter()
            .collect::<Vec<_>>();
        let kind = match discovered.get(blox_name).map(|b| b.kind) {
            Some(util::BloxSourceKind::PureToml) => DepKind::GeneratedBlox,
            _ => DepKind::Resolved,
        };
        deps.insert(blox_name.clone(), (features, kind));

        if is_timer {
            // bloxide-timer is already added as the blox crate.
            // Ensure std feature is included.
            let entry = deps
                .get_mut("bloxide-timer")
                .ok_or_else(|| anyhow::anyhow!("timer actor requires bloxide-timer dependency"))?;
            if !entry.0.contains(&"std".to_string()) {
                entry.0.push("std".to_string());
            }
        }

        // Message crates: extract from the blox.toml's event.mailboxes[].message_path.
        // A message_path may reference multiple crates in nested generics, e.g.
        // "pool_messages::SpawnedWorker<bloxide_peers::PeerCtrl<...>, R>" — we
        // need all of them as Cargo.toml dependencies.
        if let Some(blox_config) = blox_configs.get(blox_name) {
            if let Some(event) = &blox_config.event {
                for mailbox in &event.mailboxes {
                    let path = mailbox.message_path.as_deref().unwrap_or(&mailbox.message);
                    for crate_part in extract_crates_from_path(path) {
                        let cargo_name = crate_part.replace('_', "-");
                        deps.entry(cargo_name)
                            .or_insert_with(|| (vec![], DepKind::Resolved));
                    }
                }
            }

            // Also check context.imports for message crate references.
            if let Some(ctx) = &blox_config.context {
                for imp in &ctx.imports {
                    // imports are like "ping_pong_messages::PingPongMsg"
                    // or "bloxide_timer::{TimerCommand, TimerId}"
                    if let Some(crate_part) = imp.split("::").next() {
                        // Skip std/alloc/bloxide_core etc — only add external
                        // message crates (they end with "_messages").
                        if crate_part.ends_with("_messages") {
                            let cargo_name = crate_part.replace('_', "-");
                            deps.entry(cargo_name)
                                .or_insert_with(|| (vec![], DepKind::Resolved));
                        }
                    }
                }

                // Add context action crates — these are the crates that
                // provide the concrete action functions referenced in the
                // generated spec_skeleton.rs (e.g. blox_ctx_rounds,
                // blox_ctx_ping_pong, bloxide_timer).
                for action in &ctx.actions {
                    if let Some(ref crate_name) = action.crate_name {
                        let cargo_name = crate_name.replace('_', "-");
                        deps.entry(cargo_name)
                            .or_insert_with(|| (vec![], DepKind::Resolved));
                    }
                }
            }
        }

        // Concrete action impl crate (system codegen). Forward the actor's
        // features to the impl crate so that feature-gated action functions
        // are compiled in.
        if let Some(impl_crate) = &actor.impl_crate {
            let cargo_name = impl_crate.replace('_', "-");
            let entry = deps
                .entry(cargo_name)
                .or_insert_with(|| (vec![], DepKind::Resolved));
            for feat in &actor.features {
                if !entry.0.contains(feat) {
                    entry.0.push(feat.clone());
                }
            }
        }

        // Factory injection crates.
        for src in actor.inject.values() {
            if src.source == "factory" {
                if let Some(crate_name) = &src.crate_name {
                    // crate_name uses underscores (e.g. "tokio_pool_demo_impl")
                    // — convert to hyphens for Cargo.toml.
                    let cargo_name = crate_name.replace('_', "-");
                    deps.entry(cargo_name)
                        .or_insert_with(|| (vec![], DepKind::Resolved));
                }
                // The generated main.rs composes the factory with the
                // platform spawn (`::bloxide_spawn::spawn_actor_task`), so
                // the example needs bloxide-spawn as a direct dependency.
                deps.entry("bloxide-spawn".to_string())
                    .or_insert_with(|| (std_features.clone(), DepKind::Resolved));
            }
        }
    }

    Ok(deps)
}

/// External (version-based) dependency specs from the workspace root's
/// `[workspace.dependencies]` table: crate name → raw TOML value.
fn workspace_version_deps(workspace_root: &Path) -> anyhow::Result<BTreeMap<String, toml::Value>> {
    let content = std::fs::read_to_string(workspace_root.join("Cargo.toml"))?;
    let parsed: toml::Value = toml::from_str(&content)?;
    let mut map = BTreeMap::new();
    if let Some(deps) = parsed
        .get("workspace")
        .and_then(|w| w.get("dependencies"))
        .and_then(|d| d.as_table())
    {
        for (name, value) in deps {
            if value.get("path").is_none() {
                map.insert(name.clone(), value.clone());
            }
        }
    }
    Ok(map)
}

/// Render one dependency line for the example manifest.
fn dep_line(
    name: &str,
    features: &[String],
    kind: DepKind,
    prefix: &str,
    ws_paths: &BTreeMap<String, String>,
    ws_versions: &BTreeMap<String, toml::Value>,
) -> anyhow::Result<String> {
    let feat_suffix = |features: &[String]| {
        if features.is_empty() {
            String::new()
        } else {
            format!(", features = {}", toml_string_list(features))
        }
    };

    match kind {
        DepKind::GeneratedBlox => {
            // From examples/<name> to crates/<blox>: ../../crates/<blox>.
            Ok(format!(
                "{} = {{ path = \"../../crates/{}\"{} }}\n",
                name,
                name,
                feat_suffix(features)
            ))
        }
        DepKind::Resolved => {
            if let Some(path) = ws_paths.get(name) {
                Ok(format!(
                    "{} = {{ path = \"{}{}\"{} }}\n",
                    name,
                    prefix,
                    path,
                    feat_suffix(features)
                ))
            } else if let Some(value) = ws_versions.get(name) {
                Ok(render_version_dep(name, value, features))
            } else {
                anyhow::bail!(
                    "dependency \"{}\" (required by the system.toml) has no entry in the workspace root's [workspace.dependencies]",
                    name
                )
            }
        }
        DepKind::InlineVersion => {
            // Inline version specs for non-workspace deps (embassy crates).
            let feats = feat_suffix(features);
            let line = match name {
                "cortex-m-rt" => "cortex-m-rt = { version = \"=0.7.6\" }\n".into(),
                "embassy-executor" => {
                    format!("embassy-executor = {{ version = \"0.9\"{} }}\n", feats)
                }
                "embassy-sync" => format!("embassy-sync = {{ version = \"0.7\"{} }}\n", feats),
                "embassy-time" => format!("embassy-time = {{ version = \"0.5\"{} }}\n", feats),
                "critical-section" => {
                    format!("critical-section = {{ version = \"1.2\"{} }}\n", feats)
                }
                _ => anyhow::bail!("no inline version spec known for dependency \"{}\"", name),
            };
            Ok(line)
        }
    }
}

/// Render an external dependency, copying the version spec from the root
/// `[workspace.dependencies]` entry verbatim (string or inline table form),
/// merging any extra features the example requires.
fn render_version_dep(name: &str, value: &toml::Value, extra_features: &[String]) -> String {
    match value {
        toml::Value::String(version) => {
            if extra_features.is_empty() {
                format!("{} = \"{}\"\n", name, version)
            } else {
                format!(
                    "{} = {{ version = \"{}\", features = {} }}\n",
                    name,
                    version,
                    toml_string_list(extra_features)
                )
            }
        }
        toml::Value::Table(table) => {
            let version = table.get("version").and_then(|v| v.as_str());
            let mut features: Vec<String> = table
                .get("features")
                .and_then(|f| f.as_array())
                .map(|arr| {
                    arr.iter()
                        .filter_map(|f| f.as_str().map(String::from))
                        .collect()
                })
                .unwrap_or_default();
            for feat in extra_features {
                if !features.contains(feat) {
                    features.push(feat.clone());
                }
            }
            let mut parts = Vec::new();
            if let Some(version) = version {
                parts.push(format!("version = \"{}\"", version));
            }
            if !features.is_empty() {
                parts.push(format!("features = {}", toml_string_list(&features)));
            }
            format!("{} = {{ {} }}\n", name, parts.join(", "))
        }
        _ => format!("{} = {}\n", name, value),
    }
}

/// Render the materialized example crate's `Cargo.toml`.
pub fn example_manifest(
    config: &SystemConfig,
    crate_name: &str,
    discovered: &BTreeMap<String, util::DiscoveredBlox>,
    blox_configs: &BTreeMap<String, BloxConfig>,
    workspace_root: &Path,
    example_dir: &Path,
    dev_crates: &BTreeSet<String>,
) -> anyhow::Result<String> {
    let mut ws_paths = workspace_dep_paths(workspace_root)?;
    for (name, value) in crate::packages::dependencies(workspace_root)? {
        if let Some(path) = value.get("path").and_then(|p| p.as_str()) {
            ws_paths.insert(name, path.into());
        }
    }
    let ws_versions = workspace_version_deps(workspace_root)?;
    let (version, edition, license) = workspace_package_values(workspace_root);
    let prefix = relative_prefix(workspace_root, example_dir)?;

    let mut out = String::new();
    out.push_str(MANIFEST_HEADER);
    out.push('\n');
    out.push_str("[package]\n");
    out.push_str(&format!("name = \"{}\"\n", crate_name));
    out.push_str(&format!("version = \"{}\"\n", version));
    out.push_str(&format!("edition = \"{}\"\n", edition));
    if let Some(license) = &license {
        out.push_str(&format!("license = \"{}\"\n", license));
    }
    out.push_str("publish = false\n\n");

    // [dependencies]
    let deps = collect_dependencies(config, discovered, blox_configs)?;
    out.push_str("[dependencies]\n");
    for (name, (features, kind)) in &deps {
        if *kind == DepKind::Resolved {
            out.push_str(&crate::packages::dependency_line(
                workspace_root,
                &prefix,
                name,
                features,
                config.system.profile == "embedded",
            )?);
        } else {
            out.push_str(&dep_line(
                name,
                features,
                *kind,
                &prefix,
                &ws_paths,
                &ws_versions,
            )?);
        }
    }
    out.push('\n');

    // [dev-dependencies] — crates the integration tests import directly
    // (derived from the test sources; see module docs). The scan also yields
    // lowercase MODULE segments of multi-segment paths (e.g. `lifecycle` in
    // `bloxide_core::lifecycle::...`) — candidates that resolve to no known
    // crate (workspace dependency or discovered blox) are not crates and are
    // dropped here.
    let self_underscored = crate_name.replace('-', "_");
    let mut dev_names: Vec<String> = dev_crates
        .iter()
        .map(|u| u.replace('_', "-"))
        .filter(|name| *name != crate_name && *name != self_underscored)
        .collect();
    dev_names.sort();
    let mut dev_section = String::new();
    for name in &dev_names {
        // Kind + features mirror the [dependencies] entry when present;
        // otherwise the crate must resolve via [workspace.dependencies].
        let (features, kind) = match deps.get(name) {
            Some((features, kind)) => (features.clone(), *kind),
            None if ws_paths.contains_key(name) || ws_versions.contains_key(name) => {
                (vec![], DepKind::Resolved)
            }
            None => continue,
        };
        if kind == DepKind::Resolved {
            dev_section.push_str(&crate::packages::dependency_line(
                workspace_root,
                &prefix,
                name,
                &features,
                false,
            )?);
        } else {
            dev_section.push_str(&dep_line(
                name,
                &features,
                kind,
                &prefix,
                &ws_paths,
                &ws_versions,
            )?);
        }
    }
    if !dev_section.is_empty() {
        out.push_str("[dev-dependencies]\n");
        out.push_str(&dev_section);
        out.push('\n');
    }

    // [build-dependencies] — the codegen itself, for the re-sync build.rs.
    out.push_str("[build-dependencies]\n");
    out.push_str(&crate::packages::dependency_line(
        workspace_root,
        &prefix,
        "bloxide-codegen",
        &[],
        false,
    )?);

    if config.system.profile == "embedded" {
        let mut manifest: toml::Value = toml::from_str(&out)?;
        if let Some(deps) = manifest
            .get_mut("dependencies")
            .and_then(|d| d.as_table_mut())
        {
            for (_, value) in deps.iter_mut() {
                if let Some(version) = value.as_str() {
                    let mut table = toml::Table::new();
                    table.insert("version".into(), version.into());
                    *value = toml::Value::Table(table);
                }
                value
                    .as_table_mut()
                    .unwrap()
                    .insert("default-features".into(), false.into());
            }
        }
        out = format!("{MANIFEST_HEADER}{}", toml::to_string(&manifest)?);
    }
    Ok(out)
}

/// Render the materialized example crate's `src/lib.rs` — a uniform library
/// target exposing the system-generated concrete specs so integration tests
/// can import them (`<example>::generated::...`).
pub fn lib_rs_source(crate_name: &str) -> String {
    format!(
        "// Copyright 2025 Bloxide, all rights reserved\n\
         // Auto-generated by bloxide-codegen from system.toml — do not edit by hand; regenerate with `cargo blox generate`.\n\
         //! Library target for the `{crate_name}` example.\n\
         //!\n\
         //! Exposes the system-generated concrete specs (`src/generated/`) so the\n\
         //! integration tests in `tests/` can drive the real machines — the binary\n\
         //! (`src/main.rs`) keeps its own private `mod generated;`.\n\
         \n\
         pub mod generated;\n"
    )
}

/// Render the materialized example crate's `build.rs`. Paths are relative to
/// the crate dir (build scripts run with the package root as cwd), keeping
/// the generated tree relocatable.
pub fn build_rs_source(
    system_toml: &Path,
    workspace_root: &Path,
    example_dir: &Path,
) -> anyhow::Result<String> {
    let prefix = relative_prefix(workspace_root, example_dir)?;
    let system_rel = system_toml.strip_prefix(workspace_root).map_err(|_| {
        anyhow::anyhow!(
            "source system.toml {} is not under the workspace root {}",
            system_toml.display(),
            workspace_root.display()
        )
    })?;
    let source_dir = format!("{}{}", prefix, system_rel.parent().unwrap().display());
    let system_path = format!("{}{}", prefix, system_rel.display());

    Ok(format!(
        "// Copyright 2025 Bloxide, all rights reserved\n\
         // Auto-generated by bloxide-codegen — do not edit by hand; regenerate with `cargo blox generate`.\n\
         //! Build script: keeps this materialized crate in sync with its source\n\
         //! system.toml after the initial `cargo blox generate`. Regenerates\n\
         //! `src/main.rs`, `src/generated/`, `src/lib.rs`, and `Cargo.toml`, and\n\
         //! re-copies `tests/`, whenever the source system.toml or tests directory\n\
         //! changes — plain `cargo build` / `cargo test` / `cargo run` stay fresh\n\
         //! without re-running `cargo blox generate`.\n\
         //!\n\
         //! Note: a brand-new test file added to the source tests/ directory is\n\
         //! copied here on the next build, but cargo may need one extra invocation\n\
         //! to discover the new test target.\n\
         \n\
         fn main() {{\n\
         \x20   let system_toml = \"{system_path}\";\n\
         \x20   let tests_dir = \"{source_dir}/tests\";\n\
         \x20   println!(\"cargo:rerun-if-changed={{}}\", system_toml);\n\
         \x20   if std::path::Path::new(tests_dir).is_dir() {{\n\
         \x20       println!(\"cargo:rerun-if-changed={{}}\", tests_dir);\n\
         \x20       for entry in std::fs::read_dir(tests_dir).into_iter().flatten().flatten() {{\n\
         \x20           let path = entry.path();\n\
         \x20           if path.extension().is_some_and(|ext| ext == \"rs\") {{\n\
         \x20               println!(\"cargo:rerun-if-changed={{}}\", path.display());\n\
         \x20           }}\n\
         \x20       }}\n\
         \x20   }}\n\
         \x20   bloxide_codegen::example_crate::sync_from_source(\n\
         \x20       std::path::Path::new(system_toml),\n\
         \x20       std::path::Path::new(\"{prefix}\"),\n\
         \x20       std::path::Path::new(\".\"),\n\
         \x20   )\n\
         \x20   .expect(\"failed to regenerate example crate from system.toml\");\n\
         }}\n"
    ))
}

/// `["a", "b"]` TOML array literal.
fn toml_string_list(items: &[String]) -> String {
    let inner = items
        .iter()
        .map(|i| format!("\"{}\"", i))
        .collect::<Vec<_>>()
        .join(", ");
    format!("[{}]", inner)
}
