// Copyright 2025 Bloxide, all rights reserved
//! Public API for bloxide-codegen — generate Rust source from blox.toml specs.

pub mod blox_crate;
pub mod ctx;
pub mod edit;
mod events;
pub mod example_crate;
// Public so bloxide-core's build.rs can generate the tuple mailbox impls
// into `OUT_DIR` at build time (they are no longer emitted into
// `src/generated/` by `cargo blox generate`).
pub mod mailboxes;
mod messages;
pub mod packages;
pub mod schema;
pub mod spec_skeleton;
pub mod system_spec;
pub mod system_wiring;
mod topology;
pub mod util;

use schema::{BloxConfig, SystemConfig};
use std::collections::{BTreeMap, BTreeSet};
use std::path::Path;

/// Callback that maps an action reference to wrapper-closure tokens for its
/// use site. Threaded through topology and spec-skeleton generation.
/// Resolution can fail on malformed action declarations — errors propagate
/// up through generation rather than panicking.
pub(crate) type ActionResolver<'a> = &'a dyn Fn(
    &str,
    &str,
    &str,
    &[String],
    Option<&str>,
    bool,
) -> anyhow::Result<proc_macro2::TokenStream>;

/// Generate all artifacts from a parsed `BloxConfig`.
///
/// Returns a vector of `(filename, content)` pairs.
pub fn generate_all(
    config: &BloxConfig,
    crate_name: &str,
) -> anyhow::Result<Vec<(String, String)>> {
    let mut files = Vec::new();

    if let Some(messages) = &config.messages {
        for msg in messages {
            let code = messages::generate(msg)?;
            files.push((format!("messages_{}.rs", msg.name.to_lowercase()), code));
        }
    }

    if let Some(event) = &config.event {
        let code = events::generate(event)?;
        files.push(("events.rs".to_string(), code));
    }

    if let Some(topology) = &config.topology {
        let actor_name = config.actor.as_ref().map(|a| a.name.as_str());
        let has_feature = config
            .context
            .as_ref()
            .and_then(|c| c.feature.as_ref())
            .is_some();
        let code = topology::generate(topology, actor_name, crate_name, has_feature)?;
        files.push(("topology.rs".to_string(), code));
    }

    if let Some(context) = &config.context {
        let code = ctx::generate(context, crate_name)?;
        files.push(("ctx.rs".to_string(), code));
    }

    // spec_skeleton requires actor + topology + context, plus event info.
    // Event info can come from an [event] section OR from the context config
    // (event_name/event_generics fields — used when the event enum is
    // hand-written in a separate crate).
    if let (Some(actor), Some(topology), Some(context)) =
        (&config.actor, &config.topology, &config.context)
    {
        if context.event_name.is_some() || config.event.is_some() {
            // Blox-crate-level codegen ALWAYS produces stub spec_skeletons.
            // Concrete action closures are generated exclusively at the system
            // level from system.toml via generate_concrete_spec_files.
            let code = spec_skeleton::generate(
                actor,
                topology,
                context,
                config.event.as_ref(),
                crate_name,
                "crate",
                &spec_skeleton::resolve_action,
                None,
            )?;
            files.push(("spec_skeleton.rs".to_string(), code));
        }
    }

    // Note: `[mailboxes]` is intentionally NOT emitted here. The tuple
    // mailbox impls exist only for bloxide-core, whose build.rs generates
    // them into `OUT_DIR` at build time via `mailboxes::generate`.

    // Generate mod.rs that re-exports all generated submodules
    if !files.is_empty() {
        let mod_rs = generate_mod_rs(&files);
        files.push(("mod.rs".to_string(), mod_rs));
    }

    Ok(files)
}

fn generate_mod_rs(files: &[(String, String)]) -> String {
    let mut lines = vec![
        "// Copyright 2025 Bloxide, all rights reserved".to_string(),
        "// Auto-generated module.".to_string(),
        "// Files in this directory are generated by bloxide-codegen.".to_string(),
        "//! Generated by bloxide-codegen from blox.toml — do not edit by hand; regenerate with `cargo blox generate`.".to_string(),
    ];

    for (filename, _) in files {
        if filename == "mod.rs" {
            continue;
        }
        let stem = filename.strip_suffix(".rs").unwrap_or(filename);
        // topology.rs emits #[macro_export] macros (e.g. *_handler_table!).
        // #[macro_use] makes them available to sibling modules (spec_skeleton.rs).
        if stem == "topology" {
            lines.push("#[macro_use]".to_string());
        }
        lines.push(format!("pub mod {stem};"));
        lines.push(format!("#[allow(unused_imports)] pub use {stem}::*;"));
    }

    lines.join("\n") + "\n"
}

/// Parse a `blox.toml` file and generate all artifacts.
///
/// The crate name is inferred from the parent directory name.
pub fn generate_from_toml(input_path: &Path) -> anyhow::Result<Vec<(String, String)>> {
    let content = std::fs::read_to_string(input_path)?;
    let config: BloxConfig = toml::from_str(&content)?;

    let crate_name = input_path
        .parent()
        .and_then(|p| p.file_name())
        .and_then(|n| n.to_str())
        .unwrap_or("unknown")
        .to_string();

    generate_all(&config, &crate_name)
}

/// Generate the binary `main.rs` for a `system.toml` wiring manifest.
///
/// Pure: no files are written. The full example crate (Cargo.toml, build.rs,
/// src/main.rs, src/lib.rs, src/generated/, tests/) is materialized by
/// [`example_crate::sync_example`].
pub fn generate_system_wiring_from_toml(
    system_path: &Path,
    workspace_root: &Path,
) -> anyhow::Result<String> {
    let content = std::fs::read_to_string(system_path)?;
    let mut config: SystemConfig = toml::from_str(&content)?;
    packages::normalize(&mut config, workspace_root)?;

    // Discover all blox.toml files in the workspace (excluding target/).
    let blox_configs = util::discover_blox_configs(workspace_root)?;

    // Infer active features from the system.toml + blox configs.
    //
    // When an actor has a `source = "factory"` injection and the blox's
    // blox.toml declares a `feature` (e.g. "dynamic"), that feature must be
    // enabled in the example's Cargo.toml for the generated code to compile.
    let active_features = infer_active_features(&config, &blox_configs);

    system_wiring::generate(&config, &blox_configs, &active_features)
}

/// Infer which Cargo features should be enabled on each blox dependency based
/// on the system.toml and the blox configs.
///
/// Currently this detects:
/// - `dynamic` feature: when an actor has a `source = "factory"` injection
///   and the blox's blox.toml declares `feature = "dynamic"`.
///
/// Returns a map from crate name (e.g. `"pool-blox"`) to the set of features.
pub(crate) fn infer_active_features(
    config: &SystemConfig,
    blox_configs: &BTreeMap<String, BloxConfig>,
) -> BTreeMap<String, BTreeSet<String>> {
    let mut result = BTreeMap::new();

    for actor in &config.actors {
        // 1. Explicit features declared in system.toml.
        for feat in &actor.features {
            result
                .entry(actor.blox.clone())
                .or_insert_with(BTreeSet::new)
                .insert(feat.clone());
        }

        // 2. Inferred from factory injection: if the actor has a factory
        //    injection, activate the feature declared on the blox's context
        //    or event config. This is a convenience so simple cases don't
        //    need explicit features in system.toml.
        let has_factory = actor.inject.values().any(|src| src.source == "factory");

        if has_factory {
            if let Some(blox_config) = blox_configs.get(&actor.blox) {
                if let Some(ctx) = &blox_config.context {
                    if let Some(feat) = &ctx.feature {
                        result
                            .entry(actor.blox.clone())
                            .or_insert_with(BTreeSet::new)
                            .insert(feat.clone());
                    }
                }
                if let Some(event) = &blox_config.event {
                    if let Some(feat) = &event.feature {
                        result
                            .entry(actor.blox.clone())
                            .or_insert_with(BTreeSet::new)
                            .insert(feat.clone());
                    }
                }
            }
        }
    }

    result
}
