// Copyright 2025 Bloxide, all rights reserved
//! Generate `impl Mailboxes<E> for (S1, ..., SK)` for K = 1..=max_arity.

use crate::schema::MailboxesConfig;
use quote::{format_ident, quote};

fn header(max_arity: usize) -> String {
    format!(
        "// Copyright 2025 Bloxide, all rights reserved\n// Auto-generated by bloxide-codegen. Do not edit manually.\n// Generated tuple mailbox implementations for arities 1 through {max_arity}.\n\n"
    )
}

pub fn generate(config: &MailboxesConfig) -> anyhow::Result<String> {
    let n = config.max_arity;
    let mut tokens = proc_macro2::TokenStream::new();

    tokens.extend(quote! {
        use crate::mailboxes::Mailboxes;
    });

    for arity in 1..=n {
        let type_params: Vec<proc_macro2::Ident> =
            (1..=arity).map(|i| format_ident!("S{}", i)).collect();
        let indices: Vec<syn::Index> = (0..arity).map(syn::Index::from).collect();

        let from_bounds: Vec<_> = type_params
            .iter()
            .map(|tp| quote! { ::core::convert::From<#tp::Item> })
            .collect();
        let stream_bounds: Vec<_> = type_params
            .iter()
            .map(|tp| quote! { #tp: ::futures_core::Stream + Unpin + Send + 'static })
            .collect();
        let item_bounds: Vec<_> = type_params
            .iter()
            .map(|tp| quote! { #tp::Item: Send + 'static })
            .collect();

        let match_arms: Vec<_> = type_params
            .iter()
            .zip(indices.iter())
            .map(|(_tp, idx)| {
                quote! {
                    match ::core::pin::Pin::new(&mut self.#idx).poll_next(cx) {
                        ::core::task::Poll::Ready(::core::option::Option::Some(item)) => {
                            return ::core::task::Poll::Ready(::core::option::Option::Some(E::from(item)));
                        }
                        ::core::task::Poll::Ready(::core::option::Option::None) => {
                            closed += 1;
                        }
                        ::core::task::Poll::Pending => {}
                    }
                }
            })
            .collect();

        let arity_lit = syn::LitInt::new(&arity.to_string(), proc_macro2::Span::call_site());

        tokens.extend(quote! {
            impl<E, #(#type_params),*> Mailboxes<E> for (#(#type_params,)*)
            where
                E: Send + 'static #(+ #from_bounds)*,
                #(#stream_bounds,)*
                #(#item_bounds,)*
            {
                fn poll_next(
                    &mut self,
                    cx: &mut ::core::task::Context<'_>,
                ) -> ::core::task::Poll<::core::option::Option<E>> {
                    // All-streams-close semantics (issue #134): a closed stream
                    // does NOT shut down the actor by itself. Streams are polled
                    // in priority order; the first ready item wins. `Ready(None)`
                    // is returned only when EVERY stream has closed — meaning no
                    // domain sender remains anywhere, so the actor cannot be
                    // reached at all. Streams must be fused: once closed, a
                    // stream must keep returning `Ready(None)` on re-poll.
                    let mut closed = 0usize;
                    #(#match_arms)*
                    if closed == #arity_lit {
                        return ::core::task::Poll::Ready(::core::option::Option::None);
                    }
                    ::core::task::Poll::Pending
                }
            }
        });
    }

    let raw = tokens.to_string();
    let file = syn::parse_str::<syn::File>(&raw)
        .map_err(|e| anyhow::anyhow!("syn parsing failed: {}", e))?;
    let formatted = prettyplease::unparse(&file);

    Ok(format!("{}{}", header(config.max_arity), formatted))
}
