// Copyright 2025 Bloxide, all rights reserved
//! Shared utilities for codegen modules.
//!
//! These functions are used by `events.rs`, `topology.rs`, `spec_skeleton.rs`
//! to convert between PascalCase, snake_case, and UPPER_SNAKE_CASE, and by
//! `lib.rs` for shared workspace discovery logic.

use crate::schema::BloxConfig;
use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

/// Standard copyright + auto-generated header for emitted files.
pub const HEADER: &str =
    "// Copyright 2025 Bloxide, all rights reserved\n// Auto-generated by bloxide-codegen. Do not edit manually.\n";

/// Module doc line for files generated from a `blox.toml` manifest.
pub const DOC_FROM_BLOX_TOML: &str = "//! Generated by bloxide-codegen from blox.toml — do not edit by hand; regenerate with `cargo blox generate`.\n";

/// Module doc line for files generated from a `system.toml` manifest.
pub const DOC_FROM_SYSTEM_TOML: &str = "//! Generated by bloxide-codegen from system.toml — do not edit by hand; regenerate with `cargo blox generate`.\n";

/// Extract the `[package] name = "..."` value from a Cargo.toml file.
pub fn parse_package_name(cargo_toml_path: &Path) -> Option<String> {
    let content = std::fs::read_to_string(cargo_toml_path).ok()?;
    let parsed: toml::Value = toml::from_str(&content).ok()?;
    parsed
        .get("package")?
        .get("name")?
        .as_str()
        .map(String::from)
}

/// How a discovered `blox.toml` is turned into a crate.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BloxSourceKind {
    /// Stdlib/messages crate with a hand-written Cargo.toml — codegen writes
    /// `src/generated/` in-crate (e.g. bloxide-timer, bloxide-supervisor,
    /// ping-pong-messages).
    InCrate,
    /// Pure-TOML blox (a `blox.toml`-only source under a `bloxes/`
    /// directory — the top-level `bloxes/` layout). `cargo blox generate`
    /// materializes a complete crate into
    /// `target/bloxide-generated/crates/<crate-name>`.
    PureToml,
}

/// A `blox.toml` discovered in the workspace, with its crate identity and
/// source kind.
pub struct DiscoveredBlox {
    pub config: BloxConfig,
    pub toml_path: PathBuf,
    pub kind: BloxSourceKind,
}

/// Derive the crate name for a pure-TOML blox: kebab-case actor name +
/// `"-blox"` (e.g. actor `Ping` → `ping-blox`, `BhsmTst` → `bhsm-tst-blox`).
pub fn pure_toml_crate_name(config: &BloxConfig) -> Option<String> {
    let actor = config.actor.as_ref()?;
    Some(format!("{}-blox", to_kebab_case(&actor.name)))
}

/// Convert PascalCase to kebab-case (via snake_case).
pub fn to_kebab_case(s: &str) -> String {
    to_snake_case(s).replace('_', "-")
}

/// Classify a blox.toml path: pure-TOML when it lives directly under a
/// directory named `bloxes` (top-level `bloxes/<name>/`), in-crate otherwise.
fn classify_blox_toml(toml_path: &Path) -> BloxSourceKind {
    let is_pure_toml = toml_path
        .parent()
        .and_then(|dir| dir.parent())
        .and_then(|grand| grand.file_name())
        .is_some_and(|name| name == "bloxes");
    if is_pure_toml {
        BloxSourceKind::PureToml
    } else {
        BloxSourceKind::InCrate
    }
}

/// Discover all `blox.toml` files under `workspace_root` (excluding `target/`),
/// keyed by crate name, with source-kind classification.
///
/// Also searches the source directories of path dependencies declared in the
/// workspace's root `Cargo.toml` — apps whose blox crates live OUTSIDE the
/// workspace (e.g. `bloxide-supervisor` from a separate bloxide checkout, as
/// produced by `cargo blox init`) get their blox.toml discovered the same way.
pub fn discover_bloxes(workspace_root: &Path) -> anyhow::Result<BTreeMap<String, DiscoveredBlox>> {
    let mut bloxes = BTreeMap::new();
    let mut insert = |toml_path: PathBuf, kind: BloxSourceKind| -> anyhow::Result<()> {
        let content = std::fs::read_to_string(&toml_path)?;
        let config: BloxConfig = toml::from_str(&content)?;
        let dir = toml_path.parent().unwrap();
        let key = match kind {
            BloxSourceKind::PureToml => pure_toml_crate_name(&config).ok_or_else(|| {
                anyhow::anyhow!(
                    "pure-TOML blox {} has no [actor] section — cannot derive a crate name",
                    toml_path.display()
                )
            })?,
            BloxSourceKind::InCrate => {
                let cargo_toml_path = dir.join("Cargo.toml");
                if cargo_toml_path.exists() {
                    parse_package_name(&cargo_toml_path)
                        .unwrap_or_else(|| dir.file_name().unwrap().to_string_lossy().to_string())
                } else {
                    dir.file_name().unwrap().to_string_lossy().to_string()
                }
            }
        };
        if let Some(previous) = bloxes.get(&key) {
            let previous: &DiscoveredBlox = previous;
            anyhow::ensure!(
                previous.toml_path.canonicalize()? == toml_path.canonicalize()?,
                "duplicate blox crate name '{key}'"
            );
        } else {
            bloxes.insert(
                key,
                DiscoveredBlox {
                    config,
                    toml_path,
                    kind,
                },
            );
        }
        Ok(())
    };

    for entry in walkdir::WalkDir::new(workspace_root)
        .into_iter()
        .filter_entry(|e| e.file_name() != "target")
        .filter_map(|e| e.ok())
    {
        if entry.file_name() == "blox.toml" {
            let kind = classify_blox_toml(entry.path());
            insert(entry.into_path(), kind)?;
        }
    }

    // Path-dependency source dirs from [workspace.dependencies] (and any
    // member's [dependencies] with a `path`). Each dep dir is a crate root —
    // look for its blox.toml directly. External deps are always in-crate.
    for dep_dir in path_dependency_dirs(workspace_root) {
        let blox_path = dep_dir.join("blox.toml");
        if blox_path.exists() {
            insert(blox_path, BloxSourceKind::InCrate)?;
        }
    }

    for (name, blox) in crate::packages::load(workspace_root)?.bloxes {
        if let Some(previous) = bloxes.get(&name) {
            anyhow::ensure!(
                previous.toml_path.canonicalize()? == blox.toml_path.canonicalize()?,
                "duplicate blox crate name '{name}'"
            );
        } else {
            bloxes.insert(name, blox);
        }
    }
    Ok(bloxes)
}

/// Discover all `blox.toml` files under `workspace_root` (excluding `target/`),
/// parse each, and return a map keyed by crate name (pure-TOML bloxes derive
/// their crate name from `[actor]`; in-crate blox.toml files key on the
/// sibling `Cargo.toml` package name, falling back to the directory name).
pub fn discover_blox_configs(
    workspace_root: &Path,
) -> anyhow::Result<BTreeMap<String, BloxConfig>> {
    Ok(discover_bloxes(workspace_root)?
        .into_iter()
        .map(|(k, v)| (k, v.config))
        .collect())
}

/// Collect the source directories of path dependencies declared in the
/// workspace root Cargo.toml's `[workspace.dependencies]` table.
fn path_dependency_dirs(workspace_root: &Path) -> Vec<PathBuf> {
    let mut dirs = Vec::new();
    let content = match std::fs::read_to_string(workspace_root.join("Cargo.toml")) {
        Ok(c) => c,
        Err(_) => return dirs,
    };
    let parsed: toml::Value = match toml::from_str(&content) {
        Ok(v) => v,
        Err(_) => return dirs,
    };
    if let Some(deps) = parsed
        .get("workspace")
        .and_then(|w| w.get("dependencies"))
        .and_then(|d| d.as_table())
    {
        for value in deps.values() {
            if let Some(path) = value.get("path").and_then(|p| p.as_str()) {
                let dir = if Path::new(path).is_absolute() {
                    PathBuf::from(path)
                } else {
                    workspace_root.join(path)
                };
                if dir.exists() {
                    dirs.push(dir);
                }
            }
        }
    }
    dirs
}

/// Convert PascalCase to snake_case.
pub fn to_snake_case(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 4);
    let chars: Vec<char> = s.chars().collect();
    for (i, &c) in chars.iter().enumerate() {
        if c.is_uppercase() && i > 0 {
            let prev_lower = chars[i - 1].is_lowercase() || chars[i - 1].is_ascii_digit();
            let next_lower = chars.get(i + 1).is_some_and(|c| c.is_lowercase());
            if prev_lower || (chars[i - 1].is_uppercase() && next_lower) {
                out.push('_');
            }
        }
        out.push(c.to_ascii_lowercase());
    }
    out
}

/// Convert PascalCase to UPPER_SNAKE_CASE.
pub fn to_upper_snake_case(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 4);
    let chars: Vec<char> = s.chars().collect();
    for (i, &c) in chars.iter().enumerate() {
        if c.is_uppercase() && i > 0 {
            let prev_lower = chars[i - 1].is_lowercase() || chars[i - 1].is_ascii_digit();
            let next_lower = chars.get(i + 1).is_some_and(|c| c.is_lowercase());
            if prev_lower || (chars[i - 1].is_uppercase() && next_lower) {
                out.push('_');
            }
        }
        out.push(c.to_ascii_uppercase());
    }
    out
}
