# Copyright 2025 Bloxide, all rights reserved
[package]
name = "bloxide-macros"
version.workspace = true
edition.workspace = true
description = "Procedural macros for bloxide — channels!, dyn_channels!, next_actor_id!"
repository.workspace = true
license.workspace = true

[lib]
proc-macro = true

[dependencies]
syn  = { version = "2", features = ["full"] }
quote = "1"
proc-macro2 = "1"

[dev-dependencies]
bloxide-core = { workspace = true, features = ["std"] }
futures-core = { version = "0.3", default-features = false }
