# Copyright 2025 Bloxide, all rights reserved
[package]
name = "bloxide-core"
version.workspace = true
edition.workspace = true
description = "HSM engine, topology, transition rules, capability traits — no_std"
repository.workspace = true
license.workspace = true

[features]
default = []
std     = []
tracing = ["dep:tracing"]

[dependencies]
bloxide-log = { workspace = true }
bloxide-macros = { workspace = true }
futures-core = { version = "0.3", default-features = false }
tracing = { version = "0.1", default-features = false, optional = true }

[dev-dependencies]
trybuild = "1"

[build-dependencies]
bloxide-codegen = { path = "../tools/bloxide-codegen" }
toml = "0.8"
